eosphoros-ai/DB-GPT

README.md, environment.yml, pilot/configs/model_config.py, pilot/conversation.py, pilot/model/inference.py, pilot/server/embdserver.py, pilot/server/vicuna_server.py, pilot/server/webserver.py, requirements.txt
=> First run version

pilot/configs/config.py, pilot/server/llmserver.py
* 支持用户自定义  `llmserver` 的端口
* 默认 `llmserver` 配置修改为本地的 `127.0.0.1`
=> feat: support customizing port for llmserver

.gitignore, README.md, README.zh.md, examples/embdserver.py, pilot/configs/model_config.py, pilot/conversation.py, pilot/model/adapter.py, pilot/model/chat.py, pilot/model/chatglm_llm.py, pilot/model/llm/monkey_patch.py, pilot/model/loader.py, pilot/server/chat_adapter.py, pilot/server/llmserver.py, pilot/server/webserver.py, requirements.txt
Features： multi llms support.
- model_adapter for load multi models
- chat_adapter for chat with models.
=> Features: multi llm model support.

pilot/model/loader.py
=> fix: can not answer on mac m1-> mps device

.readthedocs.yaml, requirements.txt
update readthedoc build version.
=> fix: docs version update

README.md, README.zh.md, requirements.txt
=> fix:milvus readme

docs/use_cases/knownledge_based_qa.md
=> doc:knowledge use case

.env.template, README.zh.md
The following places involve database passwords, but the default values are not consistent, which causes confusion for users:
1. README.md
2. README.zh.md
3. 3. pilot/configs/config.py
=> bugfix: Fix the issue of inconsistent database password settings.

pilot/model/llm_out/guanaco_llm.py, pilot/model/llm_out/proxy_llm.py, pilot/model/loader.py, pilot/out_parser/base.py, pilot/server/chat_adapter.py
=> feature:  guanaco stream output (#154)

pilot/model/guanaco_llm.py
=> test guanaco_llm

.env.template, pilot/configs/model_config.py, pilot/model/adapter.py, pilot/model/llm_out/falcon_llm.py, pilot/server/chat_adapter.py
We can set QUANTIZE_QLORA=True in the .env file to enable falcon's quantization model
=> Add support for falcon

README.md, docs/getting_started/concepts.md, docs/getting_started/tutorials.md, docs/locales/zh_CN/LC_MESSAGES/getting_started/tutorials.po, docs/locales/zh_CN/LC_MESSAGES/modules/knownledge.po, pilot/language/lang_content_mapping.py
1. change the radio name with db chat
2. tutorials doc update
=> fix:db chat

pilot/scene/chat_knowledge/default/chat.py, tools/knowlege_init.py
1.fix default knowledge init error
2.knowledge_init.py bug
=> fix:default knowledge init error

pilot/configs/config.py
=> fix:default chunk size

docs/getting_started/tutorials.md, docs/index.rst, docs/locales/zh_CN/LC_MESSAGES/getting_started/tutorials.po, docs/locales/zh_CN/LC_MESSAGES/index.po, docs/locales/zh_CN/LC_MESSAGES/modules/connections.po, docs/locales/zh_CN/LC_MESSAGES/modules/connections/mysql/mysql_connection.po, docs/locales/zh_CN/LC_MESSAGES/modules/knowledge.po, docs/locales/zh_CN/LC_MESSAGES/modules/knowledge/markdown/markdown_embedding.po, docs/locales/zh_CN/LC_MESSAGES/modules/knowledge/pdf/pdf_embedding.po, docs/locales/zh_CN/LC_MESSAGES/modules/knowledge/ppt/ppt_embedding.po, docs/locales/zh_CN/LC_MESSAGES/modules/knowledge/url/url_embedding.po, docs/locales/zh_CN/LC_MESSAGES/modules/knowledge/word/word_embedding.po, docs/locales/zh_CN/LC_MESSAGES/use_cases/sql_generation_and_diagnosis.po, docs/modules/connections.md, docs/modules/connections.rst, docs/modules/connections/mysql/mysql_connection.md, docs/modules/knowledge.rst, docs/modules/knowledge/markdown/markdown_embedding.md, docs/modules/knowledge/pdf/pdf_embedding.md, docs/modules/knowledge/ppt/ppt_embedding.md, docs/modules/knowledge/url/url_embedding.md, docs/modules/knowledge/word/word_embedding.md, docs/use_cases/chatbots.md, docs/use_cases/interacting_with_api.md, docs/use_cases/sql_generation_and_diagnosis.md, pilot/source_embedding/markdown_embedding.py
1.db-gpt doc include tutorial, llm, knowledge and connections module
=> doc:db-gpt doc

docs/conf.py, pilot/model/adapter.py, pilot/model/loader.py
docs latest version set to v0.2.2,  align with code.
=> update docs latest version

docs/getting_started/getting_started.md
quick start add rely model, text-chinses-large model
=> fix: install add text-chinses-large model

docs/getting_started/tutorials.md, docs/locales/zh_CN/LC_MESSAGES/getting_started/tutorials.po
=> doc:db-gpt tutorial doc

pilot/vector_store/weaviate_store.py
The contribution aims to enhance the functionality of the DBGPT repository by integrating support for the Weaviate database. Weaviate is a vector database that provides advanced indexing and search capabilities for textual data. By incorporating Weaviate into the DBGPT repository, users will have access to efficient storage, retrieval, and similarity search features for their text-based data.
Proposed Changes:
1. Implement WeaviateStore Class:
- Create a new class, "WeaviateStore," that extends the existing vector store functionality in the DBGPT repository.
- The WeaviateStore class will serve as a wrapper around the Weaviate database and provide methods for data loading, searching, and vectorization.
- The class will utilize the Weaviate Python client library for seamless integration …
=> - add Weaviate database

README.md, README.zh.md, pilot/vector_store/weaviate_store.py
=> update:weaviate_store format

README.md, README.zh.md, docs/getting_started/getting_started.md
=> update:readme doc, put documents

docs/modules/llms.md
Fix the document by changing 'LLM_MODEL=proxy_llm' to 'LLM_MODEL=proxyllm
=> Fix the document user case 'llms'

README.zh.md, docs/getting_started/getting_started.md, docs/index.rst, docs/locales/zh_CN/LC_MESSAGES/index.po, docs/locales/zh_CN/LC_MESSAGES/modules/vector.po, docs/locales/zh_CN/LC_MESSAGES/modules/vector/chroma/chroma.po, docs/locales/zh_CN/LC_MESSAGES/modules/vector/milvus/milvus.po
Add vector docs,  provide how to use vector connector in DB-GPT.
Closes #229
=> docs: Add vector connector docs

docs/modules/vector.rst, docs/modules/vector/chroma/chroma.md, docs/modules/vector/milvus/milvus.md
Add vector docs,  provide how to you vector connector in DB-GPT. 
1.chroma docs
2.milvus docs
Closes #230
=> docs: Add chroma and milvus connector docs

setup.py
Version info update to v0.2.2
Close (#115)
=> update: setup version info

docs/modules/llms.md
Fix the name of the OpenAI proxy model in the `llms.md` document, Modifies the LLM_MODEL variable from "proxy_llm" to "proxyllm".
=> docs(openai proxy): Fix openai proxy configuration in llms.md (#233)

docs/index.rst, docs/locales/zh_CN/LC_MESSAGES/getting_started/tutorials.po, pilot/configs/model_config.py, pilot/model/adapter.py, pilot/server/llmserver.py, requirements.txt
- feat: Improve ModelWorker's error printing
- chore: bump requirement.txt for guanaco support
- docs: fix some typos in Tutorials
=> misc: update requirements.txt, polish docs, improve error logging (#234)

README.md, README.zh.md
update readme add wechat Contact Information
=> fix(contract): readme

examples/app.py, examples/gpt_index.py, examples/t5_example.py
Replace deprecated GPTSimpleVectorIndex with GPTVectorIndex 
https://github.com/jerryjliu/llama_index/issues/1900
=> -   from GPTSimpleVectorIndex to GPTVectorIndex

pilot/configs/config.py, pilot/scene/chat_knowledge/custom/chat.py, pilot/vector_store/connector.py, pilot/vector_store/weaviate_store.py, requirements.txt
1.similar search: docs format
2.conf SUMMARY_CONFIG
=> fix: Weaviate document format.

docs/getting_started/tutorials.md, docs/locales/zh_CN/LC_MESSAGES/getting_started/tutorials.po, docs/locales/zh_CN/LC_MESSAGES/index.po, docs/locales/zh_CN/LC_MESSAGES/modules/vector.po, docs/locales/zh_CN/LC_MESSAGES/modules/vector/weaviate/weaviate.po, docs/modules/vector.rst, docs/modules/vector/weaviate/weaviate.md, requirements.txt
1.requirements version
Closes #246
=> fix: requirements chromadb==0.3.22 

pilot/scene/chat_knowledge/custom/chat.py, pilot/server/webserver.py
fix custom chat exception
raise user can understand error
=> fix: custom chat exception

pilot/server/webserver.py
1.solve the problem that EMBEDDING_MODEL config did not work 
Close #264
=> fix: EMBEDDING_MODEL env config

README.md, README.zh.md, docs/conf.py, docs/getting_started/getting_started.md, docs/locales/zh_CN/LC_MESSAGES/modules/llms.po, docs/modules/llms.md, pilot/configs/model_config.py, setup.py
Add support for ChatGLM2-6B，which is the second-generation version of the open-source bilingual (Chinese-English) chat model [ChatGLM-6B](https://github.com/THUDM/ChatGLM-6B).
=> llm  support for chatglm2

pilot/model/llm_out/chatglm_llm.py
=> fix: documents chat not working with chatglm2-6b

pilot/source_embedding/knowledge_embedding.py, pilot/source_embedding/source_embedding.py, tools/knowledge_init.py
1.rebuild knowledge_init.py
2.change the VectorConnector position
Close #285
=> fix:knowledge_init.py multi document cannot search answser

pilot/model/llm_out/proxy_llm.py
=> fix: proxy llm raise exception when proxy llm response has error

pilot/configs/config.py, pilot/model/adapter.py, pilot/model/llm_out/chatglm_llm.py
=> fix: chatglm not working in doc qa, meta qa and plugin

README.md, README.zh.md, assets/schema/knowledge_management.sql, docs/faq.md, docs/getting_started/getting_started.md, docs/index.rst, docs/locales/zh_CN/LC_MESSAGES/faq.po, docs/locales/zh_CN/LC_MESSAGES/getting_started/getting_started.po, docs/locales/zh_CN/LC_MESSAGES/index.po
1.AutoDL Image
2.mock chat data sql
3.FAQ
=> doc:AutoDL Image and FAQ

docs/modules/llms.md, pilot/configs/model_config.py, pilot/model/adapter.py, pilot/model/conversation.py, pilot/model/inference.py, pilot/model/llm_out/proxy_llm.py, pilot/model/llm_utils.py, pilot/out_parser/base.py, pilot/scene/base_chat.py, pilot/scene/base_message.py, pilot/server/chat_adapter.py, pilot/server/llmserver.py
=> feat: Support llama-2 model

pilot/configs/config.py, pilot/prompts/prompt_registry.py, pilot/scene/base_chat.py, pilot/scene/chat_dashboard/prompt.py, pilot/scene/chat_db/auto_execute/prompt.py, pilot/scene/chat_db/professional_qa/prompt.py, pilot/scene/chat_execution/prompt.py, pilot/scene/chat_knowledge/custom/prompt.py, pilot/scene/chat_knowledge/default/prompt.py, pilot/scene/chat_knowledge/inner_db_summary/prompt.py, pilot/scene/chat_knowledge/v1/prompt.py, pilot/scene/chat_knowledge/v1/prompt_chatglm.py, pilot/scene/chat_normal/prompt.py
=> feat: Multi-model prompt adaptation

pilot/connections/rdbms/rdbms_connect.py
1.DDL run result query bug fix
2.DML code function change bug fix
=> <fix>DML and DDL run bug fix

.env.template, README.md, README.zh.md, docs/modules/llms.md, pilot/common/formatting.py, pilot/configs/config.py, pilot/configs/model_config.py, pilot/model/adapter.py, pilot/model/conversation.py, pilot/out_parser/base.py, pilot/prompts/prompt_new.py, pilot/prompts/prompt_registry.py, pilot/scene/base_chat.py, pilot/scene/chat_db/auto_execute/example.py, pilot/scene/chat_db/auto_execute/prompt_baichuan.py, pilot/server/chat_adapter.py, pilot/server/llmserver.py, requirements.txt
=> feat: support baichuan model

docker-compose.yml, docker/allinone/Dockerfile, docker/allinone/allinone-entrypoint.sh, docker/allinone/build_image.sh, docker/allinone/run.sh, docker/allinone/run_proxyllm.sh, docker/base/Dockerfile, docker/base/build_image.sh, docker/build_all_images.sh, docker/examples/my.cnf, docker/examples/sqls/case_1_student_manager.sql, docker/examples/sqls/case_2_ecom.sql, docker/examples/sqls/test_case.md, docker/examples/sqls/test_case_info.sql, docker/examples/sqls/user_config.sql, docs/getting_started/getting_started.md
=> feat: supports docker compose deployment

pilot/scene/base_chat.py, pilot/server/chat_adapter.py
=> fix: fix issue #367, ModelMessage is not JSON serializable

docs/modules/knownledge.md, tools/cli/cli_scripts.py, tools/cli/knowledge_client.py, tools/knowledge_init.py
Close #353 
Additional,  I created DB-GPT command line tool scripts which  currently supports initialization of the knowledge  documents.
And we can support more command line in the future.
=> feat: support multiple knowledge file path and skip some error in knowledge embedding

docs/faq.md, docs/locales/zh_CN/LC_MESSAGES/faq.po, docs/locales/zh_CN/LC_MESSAGES/getting_started/getting_started.po, docs/locales/zh_CN/LC_MESSAGES/modules/knownledge.po, docs/locales/zh_CN/LC_MESSAGES/modules/llms.po, docs/locales/zh_CN/LC_MESSAGES/modules/vector.po, docs/modules/vector.rst
doc:
1.add vector db use doc
2.add faq vector db use doc
=> doc: vector db use doc

docs/modules/llms.md, pilot/model/proxy/llms/bard.py
support bard proxy server for DB-GPT so that you can deploy in your PC easily.
=> Support bard proxy server.

README.md, README.zh.md, docs/index.rst, docs/locales/zh_CN/LC_MESSAGES/index.po
=> doc: update discord link address

.env.template, docker/base/Dockerfile, docker/base/build_image.sh, docker/build_all_images.sh, docs/getting_started/getting_started.md, pilot/configs/config.py, pilot/configs/model_config.py, pilot/logs.py, pilot/model/adapter.py, pilot/model/loader.py, pilot/server/llmserver.py, requirements.txt
Close #389 
**Some extra features:**
1. Configure the maximum memory used by each GPU
2. Unified model loading entry(for huggingface, llama.cpp, etc. )
3. Enhance docker image building
=> Support 8-bit quantization and 4-bit quantization

README.md, README.zh.md, docker/build_all_images.sh, docs/getting_started/getting_started.md, pilot/configs/config.py, pilot/configs/model_config.py, pilot/model/adapter.py, pilot/model/conversation.py, pilot/model/loader.py, pilot/server/chat_adapter.py, pilot/server/llmserver.py
=> feat: Support vicuna-v1.5 and WizardLM-v1.2

pilot/model/loader.py
=> fix: num_gpus referenced error for mps + cpu

README.md, README.zh.md, docs/conf.py, pilot/embedding_engine/loader/csv_loader.py, pilot/server/knowledge/document_db.py, setup.py
1.document delete bug
2.readme assets
=> fix: document delete bug

README.md, README.zh.md
=> doc:readme discord

.github/workflows/python-publish.yml, MANIFEST.in
- add docker actions (you need add the secret to the repo
- fix can not use `python -m build` for release -> (which actions release use)
=> feat: docker actions and fix can not use python -m build bug

.env.template, docker/base/Dockerfile, pilot/configs/model_config.py, pilot/model/adapter.py, pilot/model/llm/llama_cpp/llama_cpp.py, pilot/model/llm_out/llama_cpp_llm.py, pilot/model/loader.py, pilot/model/parameter.py, pilot/scene/chat_dashboard/out_parser.py, pilot/scene/chat_dashboard/prompt.py, pilot/server/chat_adapter.py, pilot/server/llmserver.py, requirements.txt, setup.py
Close #420 
- Support llama.cpp
- Configure parameters for a specific model
- Split into multiple optional dependencies
1.  Install with default dependencies: `pip install .`
2. Install with llama.cpp support: `pip install ".[llama_cpp]"`
3. Install with all dependencies: `pip install ".[all]"`
TODO: I will submit a pr about usage documentation later
=> feat: Support llama.cpp

docker/base/Dockerfile, pilot/connections/rdbms/conn_sqlite.py, pilot/connections/rdbms/tests/test_conn_sqlite.py, pilot/vector_store/connector.py, requirements.txt, requirements/test-requirements.txt, setup.py
- Fix #445 
- Split some main dependencies into optional dependencies, now llama.cpp supports running on Apple Silicon(m1) mac and X86 mac.
=> Fix SQLite bug and split some main dependencies into optional dependencies

docs/getting_started/install/llm/llama/llama_cpp.md
Document for [llama.cpp](https://github.com/eosphoros-ai/DB-GPT/pull/452).
=> doc: Add llama.cpp document

.github/workflows/docker-image-publish.yml, .github/workflows/python-publish.yml, docker/base/Dockerfile
fix: Fix error CICD config
fix: Fix docker image error
fix: Reduce docker image size
fix: remove other architecture
fix: remove llama.cpp dependencies from base image
=> fix: modify docker image CICD

docs/conf.py
=> doc:document theme

docs/getting_started/faq/deploy/deploy_faq.md, docs/getting_started/install/deploy/deploy.md, pilot/openapi/api_v1/api_v1.py, pilot/server/knowledge/api.py, pilot/server/llmserver.py, requirements.txt, scripts/examples/load_examples.bat, setup.py
Close #474 
Close #462
fix: Fix install error on linux
doc: Add torch cuda FAQ
=> feat: Support windows

README.md, README.zh.md, docs/getting_started/application/chatdb/chatdb.md, docs/getting_started/faq/chatdb/chatdb_faq.md, docs/locales/zh_CN/LC_MESSAGES/getting_started/application/chatdb/chatdb.po, docs/locales/zh_CN/LC_MESSAGES/getting_started/application/dashboard/dashboard.po, docs/locales/zh_CN/LC_MESSAGES/getting_started/faq/chatdb/chatdb_faq.po, pilot/common/schema.py, pilot/connections/manages/connection_manager.py, pilot/connections/rdbms/conn_clickhouse.py, pilot/openapi/api_v1/api_v1.py
1.add Clickhouse Connection
```
class ClickhouseConnect(RDBMSDatabase):
"""Connect Clickhouse Database fetch MetaData
Args:
Usage:
"""
```
2.chatdata document update
3.README support Windows
=> feat: Clickhouse Connection

.env.template, docs/conf.py, docs/getting_started/getting_started.md, docs/locales/zh_CN/LC_MESSAGES/getting_started/getting_started.po, pilot/configs/model_config.py, setup.py
1.add bge embedding model
2.getting start doc update
=> feat: add bge embbeding model

docs/getting_started/faq/llm/llm_faq.md, docs/locales/zh_CN/LC_MESSAGES/getting_started/faq/llm/llm_faq.po, docs/locales/zh_CN/LC_MESSAGES/getting_started/getting_started.po
1. add difference between dbgpt_server and dbgpt_server --light
=> doc:llm use faq

pilot/openapi/api_v1/api_v1.py, pilot/scene/base_chat.py, pilot/scene/chat_data/chat_excel/excel_analyze/chat.py, pilot/utils/utils.py
=> fix: Fix ChatExcel error

pilot/openapi/api_v1/api_v1.py
=> fix: Fix ChatExcel upload file error on windows

pilot/model/worker/manager.py
fix:worker_register_host parameter does not work
Close #526
=> fix:worker_register_host parameter does not work

docker-compose.yml, docker/base/Dockerfile, docker/compose_examples/cluster-docker-compose.yml, pilot/configs/config.py, pilot/configs/model_config.py, pilot/model/adapter.py, pilot/model/cli.py, pilot/model/llm_out/proxy_llm.py, pilot/model/loader.py, pilot/model/parameter.py, pilot/model/proxy/llms/bard.py, pilot/model/proxy/llms/chatgpt.py, pilot/model/proxy/llms/claude.py, pilot/model/proxy/llms/gpt4.py, pilot/model/proxy/llms/proxy_model.py, pilot/model/proxy/llms/tongyi.py, pilot/model/proxy/llms/wenxin.py, pilot/model/proxy/llms/zhipu.py, pilot/model/worker/default_worker.py, pilot/model/worker/manager.py, pilot/scripts/cli_scripts.py, pilot/server/_cli.py, pilot/server/base.py, pilot/server/dbgpt_server.py, pilot/utils/command_utils.py, pilot/utils/parameter_utils.py, pilot/utils/utils.py
1.  Multi-model with proxyllm.
2.  command line tool supports more commands.
=> feat: Multi-model support with proxyllm and add more command-cli

pilot/vector_store/base.py, pilot/vector_store/milvus_store.py
1.Milvus support space delete 
2.Milvus support delete by ids
Close #534
=> feat(ChatKnowledge): Milvus support collection delete and delete by ids

README.md, README.zh.md, pilot/configs/model_config.py
=> feat(model): support Baichuan2 model

README.md, README.zh.md
update readme.zh.md display problem.
=> chore: readme format display problem fix 

.env.template, README.md, README.zh.md, docker/compose_examples/cluster-docker-compose.yml, docs/getting_started/install/llm/llm.rst, pilot/componet.py, pilot/configs/config.py, pilot/configs/model_config.py, pilot/embedding_engine/embedding_factory.py, pilot/model/adapter.py, pilot/model/cluster/embedding/loader.py, pilot/model/cluster/worker/embedding_worker.py, pilot/model/cluster/worker/manager.py, pilot/model/cluster/worker/remote_worker.py, pilot/model/parameter.py, pilot/server/componet_configs.py, requirements.txt, scripts/setup_autodl_env.sh, setup.py
=> feat(model): support openai embedding model

assets/schema/prompt_management.sql, pilot/server/dbgpt_server.py, pilot/server/prompt/api.py, pilot/server/prompt/prompt_manage_db.py, pilot/server/prompt/request/request.py, pilot/server/prompt/request/response.py, pilot/server/prompt/service.py
=> feat(prompt): prompt manage support

assets/schema/history.sql, pilot/configs/config.py, pilot/openapi/api_v1/api_v1.py, pilot/openapi/api_v1/feedback/api_fb_v1.py, pilot/openapi/api_v1/feedback/feed_back_db.py, pilot/openapi/api_v1/feedback/feed_back_model.py, pilot/scene/chat_knowledge/v1/chat.py, pilot/server/dbgpt_server.py
1. Support score feedback
2. Add method to return topk document source (KBQA)
=> feat(ChatKnowledge): return topk document source (KBQA)

pilot/component.py, pilot/configs/config.py, pilot/connections/manages/connection_manager.py, pilot/server/component_configs.py, pilot/server/knowledge/_cli/knowledge_client.py, pilot/server/knowledge/service.py, pilot/utils/executor_utils.py, setup.py
=> fix(core): Use thread pool to replace native  threading.Thread

pilot/connections/conn_spark.py, setup.py
1.fix: pyspark lazy load
2.fix: chromadb version
=> fix(ChatData):pyspark lazy load

pilot/scene/chat_dashboard/out_parser.py
See [here](https://github.com/eosphoros-ai/DB-GPT/pull/626#discussion_r1336569182)
=> chore: Roll back json parsing code

.gitignore, docker-compose.yml, docker/base/run_sqlite.sh, docker/base/run_sqlite_proxyllm.sh, docker/compose_examples/cluster-docker-compose.yml, docs/getting_started/install/docker/docker.md, docs/getting_started/install/llm/llm.rst, docs/getting_started/install/llm/vllm/vllm.md, docs/locales/zh_CN/LC_MESSAGES/getting_started/install/llm/vllm/vllm.po, pilot/configs/config.py, pilot/configs/model_config.py, pilot/conversation.py, pilot/model/adapter.py, pilot/model/base.py, pilot/model/cli.py, pilot/model/cluster/worker/default_worker.py, pilot/model/conversation.py, pilot/model/inference.py, pilot/model/llm/llm_utils.py, pilot/model/llm_out/guanaco_llm.py, pilot/model/llm_out/vllm_llm.py, pilot/model/llm_utils.py, pilot/model/loader.py, pilot/model/model_adapter.py, pilot/model/parameter.py, pilot/server/chat_adapter.py, pilot/utils/parameter_utils.py, pilot/utils/tests/test_parameter_utils.py, setup.py
Close #650 
**Other**
- Introduced fastchat core library to support most models supported by fastchat.
- Upgrade pytorch to `2.0.1`
=> feat(model): Support vLLM 

pilot/utils/system_utils.py
=> 增加windows 实现

pilot/model/model_adapter.py, pilot/utils/tracer/span_storage.py, pilot/utils/tracer/tests/test_base.py, pilot/utils/tracer/tests/test_span_storage.py
**Other**
- `FileSpanStorage` create file if not exist.
- Fix span unit test error.
=> fix(model): Fix load some quantization model error

pilot/model/cluster/controller/controller.py, pilot/model/cluster/worker/manager.py, pilot/model/parameter.py, pilot/server/base.py, pilot/server/dbgpt_server.py, pilot/utils/tracer/span_storage.py, pilot/utils/tracer/tests/test_span_storage.py
Close #689 
**Other:** The tracer FileSpanStorage support file roll over
=> feat(core): Support use custom log file name and tracer file name

pilot/scene/chat_knowledge/v1/chat.py
=> Fix type exception when use office ppt database

pilot/scene/chat_db/auto_execute/out_parser.py, pilot/scene/chat_db/data_loader.py
=> fix(ChatData): ChatData

pilot/connections/manages/connection_manager.py
=> bugfix(ChatData): ChatData

pilot/base_modules/agent/commands/disply_type/show_chart_gen.py, pilot/base_modules/agent/hub/agent_hub.py, pilot/base_modules/agent/plugins_util.py, pilot/base_modules/meta_data/meta_data.py, pilot/logs.py, pilot/memory/chat_history/chat_hisotry_factory.py, pilot/memory/chat_history/store_type/meta_db_history.py, pilot/openapi/api_v1/api_v1.py, pilot/scene/base_chat.py, pilot/scene/chat_agent/chat.py, pilot/scene/chat_agent/out_parser.py, pilot/scene/chat_dashboard/chat.py, pilot/scene/chat_data/chat_excel/excel_analyze/chat.py, pilot/scene/chat_data/chat_excel/excel_learning/chat.py, pilot/scene/chat_db/auto_execute/chat.py, pilot/scene/chat_db/professional_qa/chat.py, pilot/scene/chat_execution/chat.py, pilot/scene/chat_factory.py, pilot/scene/chat_knowledge/inner_db_summary/chat.py, pilot/scene/chat_knowledge/v1/chat.py, pilot/scene/chat_normal/chat.py, pilot/utils/executor_utils.py, scripts/setup_autodl_env.sh, setup.py
Close #720 
**Others**: 
- Fix chat tracer no spans bug
- Modify AutoDL setup script
=> feat(core): Enhance server request processing performance

.env.template, docs/getting_started/faq/llm/llm_faq.md, docs/locales/zh_CN/LC_MESSAGES/getting_started/faq/llm/llm_faq.po, pilot/configs/config.py, pilot/model/cluster/controller/controller.py, pilot/model/cluster/worker/default_worker.py, pilot/model/cluster/worker/embedding_worker.py, pilot/model/cluster/worker/manager.py, pilot/model/loader.py, pilot/model/model_adapter.py, pilot/model/proxy/llms/chatgpt.py, pilot/server/dbgpt_server.py, pilot/utils/parameter_utils.py, pilot/utils/utils.py
=> feat(model): Support AquilaChat2-34B

docs/modules/knowledge.md
=> Update and rename knownledge.md to knowledge.md

.env.template, pilot/configs/model_config.py, pilot/model/adapter.py, pilot/model/conversation.py, pilot/model/model_adapter.py, pilot/server/chat_adapter.py
Close #745
Support the DB-GPT-Hub trained model, codellama series .
=> feat(model) Support the DB-GPT-Hub trained mode

CODE_OF_CONDUCT
@fangyinc I have added the code of conduct file which will help future contributors to contribute in this repository.
Please review my pull request and merge it.
=> Added CODE_OF_CONDUCT file

assets/schema/knowledge_management.sql, pilot/scene/base_chat.py, pilot/scene/chat_agent/chat.py, pilot/scene/chat_dashboard/chat.py, pilot/scene/chat_data/chat_excel/excel_analyze/chat.py, pilot/scene/chat_data/chat_excel/excel_learning/chat.py, pilot/scene/chat_db/auto_execute/chat.py, pilot/scene/chat_db/auto_execute/out_parser.py, pilot/scene/chat_db/professional_qa/chat.py, pilot/scene/chat_execution/chat.py, pilot/scene/chat_knowledge/inner_db_summary/chat.py, pilot/scene/chat_knowledge/v1/chat.py, pilot/scene/chat_normal/chat.py, pilot/utils/executor_utils.py, pilot/utils/tracer/__init__.py, pilot/utils/tracer/tracer_cli.py, pilot/utils/tracer/tracer_impl.py
- More trace record for DB-GPT
- Support pass span id to threadpool
=> feat(core): More trace records for DB-GPT

docker/base/Dockerfile, docs/getting_started/install/deploy.rst, docs/locales/zh_CN/LC_MESSAGES/getting_started/install/deploy.po, docs/locales/zh_CN/LC_MESSAGES/index.po, pilot/model/cluster/worker/manager.py, pilot/model/parameter.py, pilot/model/proxy/llms/tongyi.py, pilot/server/base.py, pilot/server/dbgpt_server.py, pilot/utils/tracer/__init__.py, pilot/utils/tracer/base.py, pilot/utils/tracer/span_storage.py, pilot/utils/tracer/tests/test_span_storage.py, pilot/utils/tracer/tracer_impl.py
- Support custom trace storage
- Modify install documents
=> feat(core): Support custom trace storage

pilot/connections/rdbms/conn_clickhouse.py
1. group_concat() not supported in clickhouse, use arrayStringConcat+groupArray instead
2. escaped quotes
=> Fix(ChatData):ClickHouse connection testing problem.

pilot/model/proxy/llms/chatgpt.py
=> fix(Model): Compatible with openai 1.x.x, compatible with AzureOpeai

README.md
=> Refinement of grammar issues in README.md

pilot/model/model_adapter.py
=> fix(ChatData): code merge bug fix

pilot/openapi/api_v1/api_v1.py
=> bugfix(ChatData): code merge bug fix

pilot/vector_store/milvus_store.py
=> fix(ChatKnowledge):Milvus create collection bug

docker/examples/dashboard/test_case_mysql_data.py
Add test data for the dashboard.
How to use it?
- Create dbgpt_test database `CREATE DATABASE IF NOT EXISTS dbgpt_test CHARACTER SET utf8;`
- execute script `python docker/examples/dashboard/test_case_mysql_data.py`
=> feat(usage): add tests cases for dashboard

README.md, README.zh.md, pilot/configs/model_config.py, pilot/model/cluster/worker/default_worker.py, pilot/model/llm_out/hf_chat_llm.py, pilot/model/model_adapter.py, pilot/scene/base_message.py, setup.py
=> feat(model): Support Yi-34B-Chat

pilot/model/parameter.py, pilot/model/proxy/llms/spark.py
[detail]add interface for Spark according to the API reference default API version: V3.1
max context length: 8192
=> [summary]adapt for xunfei Spark LLM

pilot/scene/base.py
=> fix scene base 'of_mode' error

dbgpt/app/base.py, dbgpt/app/tests/test_base.py
=> fix(core): Fix not create database bug

dbgpt/storage/chat_history/chat_history_db.py
fix chat_history_db mysql message query bug
=> fix(chat_history): chat_history_db mysql message query bug

dbgpt/datasource/rdbms/conn_clickhouse.py
Fixed issue https://github.com/eosphoros-ai/DB-GPT/issues/998
=> fix(clickhouse): fix information_schema

Makefile
- Create new virtual environment only `setup.py` has changed
- Reduce unit test dependencies
=> build: Improve build performance

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Delete useless agent code. The current version is ready to be merged.
The PR template is shown as follows:
=> feat(build):Add Template for Pull Request

dbgpt/model/proxy/llms/chatgpt.py
This is a temporary solution, and there will be new PR  to solve the problem of message format conversion in next version.
=> feat(model): Fix chatgpt message format bug

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md, .github/pull_request_template.md
=> feat(build):Move PR Template in .github folder to automatically generate PR Template for each PR

dbgpt/model/llm/monkey_patch.py, dbgpt/model/loader.py
=> fix(model): Fix device MPS load llama error

CONTRIBUTING.md, dbgpt/agent/agents/agents_mange.py, dbgpt/agent/agents/expand/plugin_assistant_agent.py, dbgpt/agent/agents/expand/retrieve_summary_assistant_agent.py, dbgpt/agent/agents/expand/summary_assistant_agent.py, dbgpt/agent/agents/resource.py, dbgpt/agent/common/schema.py, dbgpt/agent/memory/gpts_memory.py, dbgpt/app/openapi/api_v1/api_v1.py, dbgpt/serve/agent/agents/controller.py, dbgpt/serve/agent/db/gpts_manage_db.py, dbgpt/vis/tags/vis_gpts_result.py
Format agent code and modify `CONTRIBUTING.md`
`make test`
=> chore: Format agent code

README.md, README.zh.md
Add contributor wall to display developer
=> chore: add contributor wall

examples/awel/simple_dbschema_retriever_example.py, examples/awel/simple_rag_embedding_example.py, examples/awel/simple_rag_retriever_example.py
EMBEDDING_MODEL parameter is text2vec, DB-GPT service startup error occurs:
```
2024-01-24 09:24:39 172-16-10-163 dbgpt.component[19815] INFO Register component with name dbgpt_awel_dag_manager and instance: <dbgpt.core.awel.dag.dag_manager.DAGManager object at 0x7fd631b642e0>
2024-01-24 09:24:39 172-16-10-163 dbgpt.core.awel.dag.loader[19815] INFO Importing /mnt/data/xiuzhu/DB-GPT/examples/awel/simple_rag_embedding_example.py
2024-01-24 09:24:39 172-16-10-163 sentence_transformers.SentenceTransformer[19815] INFO Load pretrained SentenceTransformer: /mnt/data/xiuzhu/models/text2vec
2024-01-24 09:24:39 172-16-10-163 dbgpt.core.awel.dag.loader[19815] ERROR Failed to import: /mnt/data/xiuzhu/DB-GPT/examples/awel/simple_rag_embedding_example.py, error message: Traceback (most recent call …
```
=> fix: Fix examples/awel get model_name from model_config

dbgpt/model/utils/chatgpt_utils.py
fix when add api_azure_deployment keyword ,openAI can not run
has tested
=> fix when add api_azure_deployment keyword ,openAI can not run

dbgpt/agent/actions/dashboard_action.py, dbgpt/agent/agents/expand/dashboard_assistant_agent.py, dbgpt/agent/agents/role.py, dbgpt/serve/agent/team/layout/agent_operator.py, dbgpt/serve/agent/team/layout/agent_operator_resource.py, dbgpt/serve/agent/team/plan/team_auto_plan.py, dbgpt/vis/tags/vis_dashboard.py
1.Fix the display problem under dashboard
2.Support Awel Agent to arrange fixed targets
=> Gpts app v0.4

docs/docs/upgrade/v0.5.0.md, docs/sidebars.js
Add upgrade to v0.5.0 documents.
Not need.
=> docs: Add upgrade to v0.5.0 documents

README.md, README.zh.md, dbgpt/configs/model_config.py, dbgpt/model/adapter/hf_adapter.py
Closes #1186 
Modify your `.env` file like follow and rerun DB-GPT.
```bash
LLM_MODEL=gemma-7b-it
```
=> feat(model): Support gemma model

README.md
Update display images default english.
-  Add Apps images
- Add AWEL image
- Add Dashboard image
=> Update display images default english

.env.template, dbgpt/_private/config.py, dbgpt/app/knowledge/service.py, dbgpt/app/scene/chat_knowledge/v1/chat.py, dbgpt/configs/model_config.py, dbgpt/model/__init__.py, dbgpt/model/cluster/client.py, dbgpt/rag/retriever/embedding.py, dbgpt/rag/text_splitter/text_splitter.py, dbgpt/serve/rag/assembler/base.py, dbgpt/storage/vector_store/base.py, dbgpt/storage/vector_store/connector.py, dbgpt/util/tracer/base.py
- perf(rag): Support load large document
- Add remote LLM client
`make test`
=> perf(rag): Support load large document

README.md, README.zh.md
Add docs reference for v0.5.0 at readme page.
=> docs: add new feature docs reference

dbgpt/model/cluster/worker/manager.py, dbgpt/model/parameter.py
Add support for multiple versions of the same model
Such as Spark LLM can support three version APIs, eg: api1, api2, api3
=> feat(model): Add support for multiple versions of the same model

dbgpt/datasource/rdbms/conn_doris.py
Please ref : https://github.com/eosphoros-ai/DB-GPT/issues/1307
Changes only affect to `doris` type datasouce, other datasouce can overwritw get_columns method to get same solution
yes, test against doris
- [y] My code follows the style guidelines of this project
- [y] I have performed a self-review of my own code
=> fix(datasource): Fix the bug of doris missing comments

docker/base/Dockerfile, setup.py
Fix build docker image error.
`make test`
=> fix: Fix build docker image error

README.md, README.zh.md, dbgpt/configs/model_config.py, dbgpt/model/adapter/hf_adapter.py, setup.py
Support [Starling-LM-7B-beta](https://huggingface.co/Nexusflow/Starling-LM-7B-beta).
Modify your `.env` file and restart DB-GPT webserver.
```bash
LLM_MODEL=starling-lm-7b-beta
```
=> feat(model): Support Starling-LM-7B-beta

README.md, README.zh.md, dbgpt/configs/model_config.py, dbgpt/model/adapter/hf_adapter.py, dbgpt/util/date_utils.py, requirements/dev-requirements.txt
Support  [Qwen1.5-32B](https://huggingface.co/Qwen/Qwen1.5-32B-Chat)
Modify your .env file and restart DB-GPT.
```bash
LLM_MODEL=qwen1.5-32b-chat
```
=> feat(model): Support Qwen1.5-32B

.env.template, .mypy.ini, dbgpt/_private/config.py, dbgpt/configs/model_config.py, dbgpt/core/interface/llm.py, dbgpt/model/adapter/proxy_adapter.py, dbgpt/model/proxy/__init__.py, dbgpt/model/proxy/llms/chatgpt.py, dbgpt/model/proxy/llms/moonshot.py
Support [moonshot proxy LLM](https://platform.moonshot.cn/docs/api-reference#%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B)
1. Use moonshot in DB-GPT
```bash
LLM_MODEL=moonshot_proxyllm
MOONSHOT_MODEL_VERSION=moonshot-v1-8k
MOONSHOT_API_BASE=https://api.moonshot.cn/v1
MOONSHOT_API_KEY={your-moonshot-api-key}
```
Then restart DB-GPT to use it in the web page.
2. Use `MoonshotLLMClient` in python code.
Create python file `test_moonshot_proxyllm.py`
```python
import asyncio
from dbgpt.model.proxy import MoonshotLLMClient
client = MoonshotLLMClient()
print(asyncio.run(client.generate(ModelRequest._build("moonshot-v1-8k", "你是谁？"))))
```
Run `test_moonshot_proxyllm.py`
```bash
MOONSHOT_API_KEY={your-moonshotapi-key} python test_moonshot_proxyllm.py …
```
=> feat(model): Support moonshot proxy LLM

dbgpt/agent/core/base_agent.py, dbgpt/agent/expand/code_assistant_agent.py, dbgpt/agent/resource/resource_db_api.py, dbgpt/agent/util/__init__.py, dbgpt/app/dbgpt_server.py, dbgpt/component.py, dbgpt/model/cluster/worker/manager.py, dbgpt/util/tracer/base.py, dbgpt/util/tracer/span_storage.py, dbgpt/util/tracer/tests/test_tracer_impl.py, dbgpt/util/tracer/tracer_impl.py, dbgpt/vis/__init__.py, docs/docs/agents/cookbook/calculator_with_agents.md, docs/docs/agents/custom_agents.md, docs/sidebars.js, examples/agents/awel_layout_agents_chat_examples.py, examples/agents/single_agent_dialogue_example.py, examples/agents/sql_agent_dialogue_example.py, setup.py
- Add trace for agent
- Add agents cookbook
1. Restart your DB-GPT
2. Run `Agent Chat` in web page.
3. Show agent trace log by command.
`dbgpt trace list --span_type agent`
=> feat(agent): Add trace for agent

README.md, README.zh.md, dbgpt/configs/model_config.py
Support [CodeQwen1.5-7B-Chat](https://huggingface.co/Qwen/CodeQwen1.5-7B-Chat)
Closes #1429 
Modify your .env file and restart DB-GPT.
```
LLM_MODEL=codeqwen1.5-7b-chat
```
=> feat(model): Support CodeQwen1.5-7B-Chat

README.md, README.zh.md, dbgpt/configs/model_config.py, dbgpt/datasource/rdbms/conn_clickhouse.py, dbgpt/model/adapter/hf_adapter.py, dbgpt/model/llm_out/hf_chat_llm.py, setup.py
Closes #1434
Modify your `.env`:
```bash
LLM_MODEL=meta-llama-3-8b-instruct
```
=> feat(model): Support Llama-3

dbgpt/rag/retriever/rerank.py, examples/rag/cross_encoder_rerank_example.py
Close #1437, #1339 
- add cross-encoder rerank
1. download bge-base rerank model at https://huggingface.co/BAAI/bge-reranker-base 
or bce-base model at https://huggingface.co/maidalun1020/bce-reranker-base_v1, and put model in `DB-GPT/models/`
reference: https://github.com/netease-youdao/BCEmbedding
2. `python examples/rag/cross_encoder_rerank_example.py`
```bash
after cross-encoder rerank results:
----1.chunk content:"What is AWEL?": Agentic Workflow Expression Language(AWEL) is a set of intelligent agent workflow expression language specially designed for large model application
development. It provides great functionality and flexibility. Through the AWEL API, you can focus on the development of business logic for LLMs applications
without paying attention to cumbersome model and …
```
=> feat(RAG):add cross-encoder rerank

dbgpt/_version.py, setup.py
=> chore:v0.5.5 tag

README.md, README.zh.md, dbgpt/configs/model_config.py
Closes #1473
`LLM_MODEL=qwen1.5-110b-chat`
=> feat(model): Qwen110B

dbgpt/storage/vector_store/chroma_store.py, dbgpt/storage/vector_store/pgvector_store.py, docs/docs/installation/advanced_usage/ollama.md, docs/sidebars.js
=> doc:ollama document

dbgpt/core/interface/knowledge.py, dbgpt/rag/embedding/_wrapped.py, dbgpt/rag/knowledge/url.py, dbgpt/storage/vector_store/chroma_store.py, dbgpt/storage/vector_store/pgvector_store.py, docs/docs/installation/advanced_usage/ollama.md, docs/sidebars.js, setup.py
=> style: code format

.mypy.ini
=> style: mypy import error

README.md, README.zh.md, dbgpt/configs/model_config.py, dbgpt/model/adapter/base.py, dbgpt/model/adapter/hf_adapter.py
Closes #1514 
Modify `.env`
```bash
LLM_MODEL=yi-1.5-6b-chat
```
Then restart DB-GPT.
=> feat(model): Support Yi-1.5 models

dbgpt/rag/knowledge/__init__.py, dbgpt/rag/knowledge/base.py, dbgpt/rag/knowledge/excel.py, dbgpt/rag/knowledge/factory.py
=> [Feature] ChatKnowledge Support Excel Document

assets/schema/upgrade/v_0_5_6/upgrade_to_v0.5.6.sql, assets/schema/upgrade/v_0_5_6/v0.5.5.sql, dbgpt/agent/expand/actions/tool_action.py, dbgpt/agent/resource/manage.py, dbgpt/util/dbgpts/base.py, dbgpt/util/dbgpts/loader.py, dbgpt/util/dbgpts/template.py
Now we can install `resource` from dbgpts.
1. Install `simple-calculator-example` tool
```bash
dbgpt app install simple-calculator-example -U
```
2.  Then you create a new APP with tool `simple-calculator-example`
=> feat: Support resource for dbgpts

docker/allinone/Dockerfile
Closes #1521 
```bash
bash docker/build_all_images.sh
```
=> fix(build): Fix build allinone images error

dbgpt/storage/vector_store/connector.py
multi client error
add and delete datasource
=> fix:multi client error

dbgpt/configs/model_config.py, dbgpt/model/adapter/hf_adapter.py, scripts/setup_autodl_env.sh
Support [DeepSeek-V2-Lite-Chat](https://huggingface.co/deepseek-ai/DeepSeek-V2-Lite-Chat).
```bash
LLM_MODEL=deepseek-v2-lite-chat
```
=> feat(model): Support DeepSeek v2 lite model

dbgpt/configs/model_config.py
Support [Yi-1.5-9B-Chat-16K](https://huggingface.co/01-ai/Yi-1.5-9B-Chat-16K) and [Yi-1.5-34B-Chat-16K](https://huggingface.co/01-ai/Yi-1.5-34B-Chat-16K)
Modfiy `.env` file:
```bash
LLM_MODEL=yi-1.5-9b-chat-16k
```
=> feat(model): Support Yi 1.5 16k models

README.md, README.zh.md, dbgpt/configs/model_config.py, dbgpt/model/adapter/hf_adapter.py, dbgpt/model/llm_out/hf_chat_llm.py
- Support [Phi-3 models](https://huggingface.co/collections/microsoft/phi-3-6626e15e9585a200d2d761e3)
- Support [Sailor-14B-Chat](https://huggingface.co/sail/Sailor-14B-Chat)
```bash
LLM_MODEL=phi-3-medium-128k-instruct
```
=> feat(model): Support Phi-3 models

dbgpt/app/knowledge/api.py, dbgpt/app/knowledge/service.py, dbgpt/rag/assembler/embedding.py, dbgpt/rag/index/base.py, dbgpt/serve/rag/service/service.py, dbgpt/storage/knowledge_graph/knowledge_graph.py, dbgpt/storage/vector_store/base.py, dbgpt/storage/vector_store/chroma_store.py, dbgpt/storage/vector_store/connector.py, dbgpt/storage/vector_store/elastic_store.py, dbgpt/storage/vector_store/milvus_store.py, dbgpt/storage/vector_store/oceanbase_store.py, dbgpt/storage/vector_store/pgvector_store.py, dbgpt/storage/vector_store/weaviate_store.py
Close #1541 
- add aload_document
ChatKnowledge upload file.
=> fix(ChatKnowledge): add aload_document

dbgpt/configs/model_config.py, dbgpt/model/adapter/hf_adapter.py
Closes #547 
```bash
LLM_MODEL=llama-3-sqlcoder-8b
```
=> feat(model): Support llama-3-sqlcoder-8b

dbgpt/configs/model_config.py, dbgpt/model/adapter/hf_adapter.py
Support [openchat-3.6-8b-20240522](https://huggingface.co/openchat/openchat-3.6-8b-20240522)
```bash
LLM_MODEL=openchat-3.6-8b-20240522
```
=> feat(model): Support openchat-3.6-8b-20240522

web/components/common/completion-input.tsx
Home Q&A box shift+center will appear line feed multiple line problem
=> fix: Fix the problem of multiple line breaks in Q&A

dbgpt/_version.py, dbgpt/app/scene/chat_dashboard/data_loader.py, dbgpt/configs/model_config.py, dbgpt/rag/assembler/bm25.py, dbgpt/rag/retriever/bm25.py, setup.py
v0.5.7 tag
make fmt-check
make mypy
=> style:fmt and v0.5.7 tag

README.ja.md, README.md
I created Japanese translated README.
=> docs:  add Japanese README

dbgpt/model/adapter/vllm_adapter.py, dbgpt/model/llm_out/vllm_llm.py
Closes #1600 
```bash
LLM_MODEL=qwen-1.8b-chat
MODEL_TYPE=vllm
```
Restart DB-GPT.
=> fix(model): Fix vllm new tokenizer error

dbgpt/rag/knowledge/datasource.py, dbgpt/rag/summary/db_summary_client.py
=> FIX:1598 Use PageTextSplitter for DatasourceKnowledge

README.ja.md, README.md, README.zh.md, dbgpt/configs/model_config.py, dbgpt/model/adapter/hf_adapter.py
Closes #1608 
```bash
LLM_MODEL=qwen2-72b-instruct
```
Then restart your DB-GPT webserver.
=> feat(model): Support Qwen2 models

.env.template, dbgpt/_private/config.py, dbgpt/agent/expand/resources/search_tool.py, docker-compose.yml, docker/base/run_sqlite.sh, docker/compose_examples/cluster-docker-compose.yml, docs/docs/installation/advanced_usage/OpenAI_SDK_call.md, docs/docs/installation/advanced_usage/vLLM_inference.md, docs/docs/installation/docker.md, docs/docs/installation/model_service/cluster.md, docs/docs/installation/model_service/stand_alone.md, docs/docs/installation/sourcecode.md, docs/docs/quickstart.md, examples/agents/custom_tool_agent_example.py, scripts/setup_autodl_env.sh
Update the default model to glm-4-9b-chat.
=> chore(model): Update the default model to glm-4-9b-chat

dbgpt/rag/schemalinker/schema_linking.py
Closes #1633
See [simple_nl_schema_sql_chart_example#L18](https://github.com/fangyinc/DB-GPT/blob/a9b3e41463527e94d0cda72ceb59993c7ce51ee6/examples/awel/simple_nl_schema_sql_chart_example.py#L18)
=> fix(rag): Fix schema linking error

web/app/i18n.ts, web/components/chart/autoChart/charts/util.ts, web/components/chart/autoChart/index.tsx, web/components/chart/helpers/downloadChartImage.ts
1.add download button to download image of chart
2. fix auto line chart when there are data points with value '-'
=> feat(web): add download image function&fix null data point

README.ja.md, README.md, README.zh.md, dbgpt/configs/model_config.py, dbgpt/model/adapter/base.py, dbgpt/model/adapter/hf_adapter.py, dbgpt/model/cluster/worker/default_worker.py, dbgpt/model/llm_out/hf_chat_llm.py
- Support gemma-2 models
- Support DeepSeek-Coder-V2-Instruct
Install latest transformers.
```
pip install -U "transformers>=4.42.1"
```
```bash
LLM_MODEL=gemma-2-9b-it
```
```bash
LLM_MODEL=deepseek-coder-v2-lite-instruct
```
=> feat(model): Support gemma-2 model

dbgpt/util/utils.py
Fixed the bug that some logs could not be written to files
Restart DB-GPT,  and you will see that most logs are written to file `logs/dbgpt_webserver.log`
=> fix(core): Fix write log files bug

dbgpt/rag/index/base.py, dbgpt/rag/retriever/embedding.py
Close #1703 
Chat knowledge with TuGraph again
=> fix: FIx GraphRAG build error

dbgpt/model/cluster/worker/remote_worker.py, dbgpt/rag/embedding/embeddings.py, dbgpt/rag/embedding/rerank.py
Fix the error when set `span_id=None` in http headers.
```bash
make test
```
=> fix: Fix http empty headers error

dbgpt/configs/model_config.py, dbgpt/model/adapter/hf_adapter.py
Support [codegeex4-all-9b](https://huggingface.co/THUDM/codegeex4-all-9b)
1. Modify `.env`
```bash
LLM_MODEL=codegeex4-all-9b
```
2. Restart your DB-GPT
=> feat(model): Support codegeex4-all-9b

dbgpt/configs/model_config.py, dbgpt/model/adapter/hf_adapter.py
Support [internlm2_5-7b-chat](https://huggingface.co/internlm/internlm2_5-7b-chat) and [internlm2_5-7b-chat-1m](https://huggingface.co/internlm/internlm2_5-7b-chat-1m)
```bash
LLM_MODEL=internlm2_5-7b-chat
```
=> feat(model): Support internlm2.5 models

dbgpt/app/openapi/api_v1/api_v1.py, requirements/dev-requirements.txt
Closes #1751 
Verify using the "Chat  Knowledge" feature on the web page.
=> fix(ChatKnowledge): Fix chat knowledge error

dbgpt/configs/model_config.py, dbgpt/model/adapter/hf_adapter.py
- Support [Mistral-Nemo-Instruct-2407](https://huggingface.co/mistralai/Mistral-Nemo-Instruct-2407)
- Support [gemma-2-2b-it](https://huggingface.co/google/gemma-2-2b-it)
```bash
LLM_MODEL=mistral-nemo-instruct-2407
```
=> feat(model): Support mistral nemo

dbgpt/serve/rag/service/service.py
Fix pylint check error.
```bash
make fmt-check
```
=> fix(ci): Fix pylint check error

web/components/flow/node-param-handler.tsx, web/components/flow/node-renderer/index.ts, web/components/flow/node-renderer/slider.tsx, web/components/flow/node-renderer/sliderList.tsx, web/components/flow/node-renderer/textarea.tsx, web/components/flow/node-renderer/timePicker.tsx, web/components/flow/node-renderer/treeSelect.tsx, web/types/flow.ts, web/utils/flow.ts
=> feat: add atom component to flow(textArea、treeSelect、timePiceker、slider)

web/components/flow/node-param-handler.tsx, web/components/flow/node-renderer/date-picker.tsx
=> fix: 1、components treeSelect and Password switch locations 2、remove console

web/components/flow/node-renderer/slider.tsx, web/components/flow/node-renderer/tree-select.tsx
=> fix: Components slider and treeSelect drag

web/components/flow/node-renderer/slider.tsx
=> fix: remove tooltip

web/components/flow/canvas-node.tsx, web/components/flow/node-renderer/upload.tsx
=> fix: upload Output format String

web/components/flow/node-renderer/upload.tsx
=> fix:upload parameter transfer array type

web/components/flow/canvas-node.tsx, web/components/flow/node-param-handler.tsx, web/components/flow/node-renderer/date-picker.tsx, web/components/flow/node-renderer/time-picker.tsx, web/components/flow/node-renderer/upload.tsx
=> fix: matching parameters of Upload component、fixed date formatting and Reduced reference

.mypy.ini, dbgpt/model/adapter/embeddings_loader.py, dbgpt/model/parameter.py, dbgpt/rag/embedding/__init__.py, dbgpt/rag/embedding/embeddings.py, setup.py
=> chore: Fix pylint error

web/components/flow/canvas-modal/import-flow-modal.tsx
=> fix: Open the popup reset import

dbgpt/agent/core/action/base.py, dbgpt/agent/core/action/blank_action.py, dbgpt/agent/core/agent_manage.py, dbgpt/agent/core/base_agent.py, dbgpt/agent/core/plan/plan_action.py, dbgpt/agent/expand/actions/chart_action.py, dbgpt/agent/expand/actions/code_action.py, dbgpt/agent/expand/actions/dashboard_action.py, dbgpt/agent/expand/actions/indicator_action.py, dbgpt/agent/expand/actions/tool_action.py, dbgpt/agent/resource/knowledge.py, dbgpt/app/openapi/api_v1/api_v1.py, dbgpt/app/scene/chat_data/chat_excel/excel_analyze/chat.py, dbgpt/app/scene/chat_data/chat_excel/excel_reader.py, dbgpt/datasource/manages/connect_config_db.py, dbgpt/serve/agent/agents/expand/actions/app_start_action.py, dbgpt/serve/agent/agents/expand/actions/intent_recognition_action.py, dbgpt/storage/knowledge_graph/community/community_store.py
Solve the problem of submitting bugs during agent linking, and solve the problem of not uploading documents during excel dialogue and reporting errors.
=> feat(agent):Fix agent bug

web/client/api/flow/index.ts, web/components/flow/canvas-modal/add-flow-variable-modal.tsx, web/tsconfig.json, web/types/flow.ts
=> feat: Add support for retrieving keys and variables by key in Flow API

web/components/flow/canvas-modal/flow-template-modal.tsx, web/components/flow/canvas-modal/index.ts, web/components/flow/canvas-node.tsx, web/components/flow/node-param-handler.tsx
=> fix: Eslint formatting

dbgpt/app/openapi/api_v1/api_v1.py, docker/examples/dashboard/test_case_sqlite_data.py
fix native app chat knowledge bug
create app by native mode.
=> fix: native app bug

docs/docs/application/awel.md
=> docs: Add flow usage document

dbgpt/_version.py, setup.py
=> chore:add v0.6.0 tag

.github/workflows/close-issue.yml
Our version has entered a relatively stable and regular iteration stage. Next, we will adjust the issue closing strategy to a longer period of time.
=> cli: issue close strategy update

dbgpt/util/parameter_utils.py, setup.py
Resolving duplicate dependency issues during package installation
NA
NA
- [ x ] My code follows the style guidelines of this project
- [ x ] I have already rebased the commits and make the commit message conform to the project standard.
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas
=> :bug: Resolving duplicate dependency

dbgpt/rag/index/base.py, dbgpt/storage/knowledge_graph/community_summary.py, examples/rag/graph_rag_example.py
fix GRAPH_COMMUNITY_SUMMARY_ENABLED = False error.
GRAPH_COMMUNITY_SUMMARY_ENABLED = False
=> fix: GRAPH_COMMUNITY_SUMMARY_ENABLED = False error.

dbgpt/app/scene/chat_data/chat_excel/excel_reader.py
…鿿"这个字符在 Unicode 编码中的位置比较靠后，可能会导致一些非预期的结果或者性能问题
=> fix:excel_reader.py unicode bug

dbgpt/app/knowledge/api.py
This fixes a critical directory traversal issue found by the ZeroPath.com team.
Ran / tested locally
=> Fix Critical Directory Traversal Vulnerability

dbgpt/serve/libro/service/jupyter_server_config.py, web/pages/construct/flow/libro/index.tsx
=> feat(web): set language and themes of libro & update csp for libro iframe

web/pages/construct/flow/libro/index.tsx
=> feat(web): use the same targetOrigin

docs/docs/cookbook/rag/graph_rag_app_develop.md
Update TuGraph database version to 4.5.0
=> docs(graphrag): update TuGraph database version to 4.5.0

setup.py
Closes #2013
```bash
make test
```
=> chore: Limit the version of fastapi

.github/workflows/python-publish.yml
Test success https://github.com/fangyinc/DB-GPT/actions/runs/12424014333
=> feat(ci): Add release pipy workflow

setup.py
Upgrade lyric to 0.1.6
```bash
make test
```
=> chore: Upgrade lyric version

dbgpt/serve/agent/agents/expand/app_start_assisant_agent.py
=> feat(agent):fix agent overrid bug

.github/workflows/doc-image-publish.yml, .github/workflows/pylint.yml, .github/workflows/test-python.yml
Adjust the CI pipeline to correctly handle image builds for pull requests and ensure images are pushed only when not in a PR. Additionally, modify concurrency settings to prevent cancellation of in-progress jobs.
=> fix(ci): Fix push document image error

.github/workflows/doc-image-publish.yml, .github/workflows/docker-image-publish.yml
Ensure Docker images are only removed if they exist, preventing errors during the build process.
N/A
=> fix(ci): Fix build docker image error

dbgpt/_private/config.py, dbgpt/app/base.py
```env
LOCAL_DB_HOST=xxxx.aws.tidbcloud.com
LOCAL_DB_TYPE=mysql
LOCAL_DB_NAME=dbgpt
LOCAL_DB_PORT=4000
LOCAL_DB_USER=xxx.root
LOCAL_DB_PASSWORD=xxxxxx
LOCAL_DB_SSL_VERIFY=True
```
use tidb serverless test
=> add LOCAL_DB_SSL_VERIFY for Supporting TiDB serverless

dbgpt/app/scene/base_chat.py, dbgpt/client/schema.py, dbgpt/serve/datasource/api/schemas.py
Close #2323 
run client_chat_example.py
=> fix:issue2323

dbgpt/agent/util/llm/llm_client.py
=> fix(agent): agent's llmclient bug

packages/dbgpt-core/src/dbgpt/util/i18n_utils.py
=> fix(i18n): Fix read i18n config error

packages/dbgpt-ext/src/dbgpt_ext/datasource/rdbms/conn_clickhouse.py
resolve clickhouse connection error.
Original：
Now:
=> fix(clickhouse): resolve clickhouse connection error

.github/workflows/doc-image-publish.yml, docs/Dockerfile-deploy
=> ci(docs): Fix build doc error

configs/dbgpt-graphrag.toml, configs/dbgpt-local-glm.toml, configs/dbgpt-local-llama-cpp-server.toml, configs/dbgpt-local-llama-cpp.toml, configs/dbgpt-local-qwen.toml, configs/dbgpt-local-vllm.toml, configs/dbgpt-proxy-deepseek.toml, docs/README.md, docs/docs/quickstart.md
add vllm llama_cpp docs and standardize configs
=> docs: add vllm llama_cpp docs and standardize configs

packages/dbgpt-app/pyproject.toml, packages/dbgpt-core/src/dbgpt/cli/cli_scripts.py, packages/dbgpt-core/src/dbgpt/configs/model_config.py, packages/dbgpt-core/src/dbgpt/core/interface/llm.py, packages/dbgpt-core/src/dbgpt/model/llm/llama_cpp/llama_cpp.py, packages/dbgpt-core/src/dbgpt/model/llm/llama_cpp/llama_cpp_server.py, packages/dbgpt-core/src/dbgpt/model/llm/llm_out/hf_chat_llm.py, packages/dbgpt-core/src/dbgpt/model/llm/llm_out/vllm_llm.py, packages/dbgpt-core/src/dbgpt/rag/embedding/embeddings.py, packages/dbgpt-core/src/dbgpt/util/dbgpts/cli.py, packages/dbgpt-core/src/dbgpt/util/dbgpts/repo.py, packages/dbgpt-core/src/dbgpt/util/dbgpts/template.py, packages/dbgpt-core/src/dbgpt/util/system_utils.py, packages/dbgpt-serve/src/dbgpt_serve/flow/service/share_utils.py, uv.lock
Refactor dbgpts for 0.7.0.
Closes #2396
=> refactor(dbgpts): Refactor dbgpts for 0.7.0

packages/dbgpt-app/src/dbgpt_app/initialization/serve_initialization.py, packages/dbgpt-core/src/dbgpt/core/interface/llm.py
Resolve a bug in the reasoning output and correct the handling of API keys in the application configuration. This ensures proper functionality and improves the overall stability of the application.
=> fix(model): Fix reasoning output bug

configs/dbgpt-graphrag.toml, configs/dbgpt-proxy-ollama.toml, packages/dbgpt-core/src/dbgpt/core/interface/llm.py, packages/dbgpt-core/src/dbgpt/model/proxy/llms/ollama.py, packages/dbgpt-core/src/dbgpt/model/utils/llm_utils.py
add ollama config and support ollama model output
```bash
ollama run deepseek-r1:1.5b
```
```bash
uv sync --all-packages --frozen \
--extra "base" \
--extra "proxy_ollama" \
--extra "rag" \
--extra "storage_chromadb" \
--extra "dbgpts"
```
=> refactor(ollama): add ollama config and support ollama model output

packages/dbgpt-core/pyproject.toml, uv.lock
Fix build lyric error from source.
=> fix(code): Fix build lyric error

examples/agents/react_agent_example.py, packages/dbgpt-core/src/dbgpt/agent/expand/actions/react_action.py, packages/dbgpt-core/src/dbgpt/agent/expand/react_agent.py
An Agent designed based on the ReAct concept, an enhanced version of ToolAgent
Run react_agent_example
=> feat(agents): add ReActAgent

docs/docs/quickstart.md
=> docs: add ollama docs

packages/dbgpt-app/src/dbgpt_app/scene/base_chat.py
=> fix(chat): Fix chat completions API error

packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/chroma_store.py
Close #2484 
fix issue 2484
create knowledge space with Chinese
=> fix:issue2484

packages/dbgpt-core/src/dbgpt/core/awel/__init__.py
=> chore(style): Code format

docs/Dockerfile-deploy
=> docs: Fix build doc error

README.md
This patch fix a typo in 0.70 README
=> doc: fix a typo in README

packages/dbgpt-app/src/dbgpt_app/openapi/api_v1/editor/_chat_history/meta_db_history.py, packages/dbgpt-app/src/dbgpt_app/openapi/api_v1/editor/api_editor_v1.py
This patch close #2530 by fixing the name typo
also fix a None check also causing this issue
=> fix: wrong name close #2530

packages/dbgpt-app/src/dbgpt_app/scene/chat_db/professional_qa/chat.py
This path close #2469 by fixing the type;
the root cause is from https://github.com/eosphoros-ai/DB-GPT/pull/2085/files type changing 
=> fix: clouse issue #2469 by fixing the type

packages/dbgpt-app/src/dbgpt_app/openapi/api_v1/api_v1.py
fix issue [2549](https://github.com/eosphoros-ai/DB-GPT/issues/2549)
=> fix: issue 2549

docker/base/Dockerfile, docs/docs/application/advanced_tutorial/api.md, docs/docs/application/fine_tuning_manual/text_to_sql.md, docs/docs/faq/kbqa.md, packages/dbgpt-app/src/dbgpt_app/knowledge/_cli/knowledge_client.py
This path fix some of typos using typos just an example
using tools https://github.com/crate-ci/typos
=> fix: some typos using typos

packages/dbgpt-core/src/dbgpt/model/cluster/worker/default_worker.py
=> fix: fix vllm tokenizer count error

packages/dbgpt-ext/src/dbgpt_ext/datasource/conn_tugraph.py, packages/dbgpt-ext/src/dbgpt_ext/rag/summary/gdbms_db_summary.py
This patch fix most of tugraph not work issue, there are still some issues
will fix next, follow patch https://github.com/eosphoros-ai/DB-GPT/pull/2533
=> fix: make tugraph work again

packages/dbgpt-core/src/dbgpt/agent/core/base_agent.py, packages/dbgpt-core/src/dbgpt/agent/expand/actions/react_action.py, packages/dbgpt-core/src/dbgpt/agent/expand/react_agent.py, packages/dbgpt-core/src/dbgpt/agent/resource/base.py, packages/dbgpt-core/src/dbgpt/agent/resource/pack.py, packages/dbgpt-core/src/dbgpt/agent/resource/tool/pack.py, packages/dbgpt-serve/src/dbgpt_serve/agent/resource/mcp.py
Support MCP authentication(SSE).
```python
from dbgpt.agent.resource import  MCPToolPack
tools = MCPToolPack(
"http://127.0.0.1:8000/sse"
default_headers={"Authorization": "Bearer your_token"}
)
tools2 = MCPToolPack(
"http://127.0.0.1:8000/sse"
headers = {
"http://127.0.0.1:8000/sse": {
"Authorization": "Bearer your_token"
}
}
)
```
Website:
=> feat(agent): Support MCP authentication

packages/dbgpt-app/src/dbgpt_app/openapi/api_v2.py, packages/dbgpt-app/src/dbgpt_app/scene/chat_db/professional_qa/chat.py, packages/dbgpt-serve/src/dbgpt_serve/agent/db/gpts_app.py
=> Fix ChatWithDbQA param validate

docker/base/Dockerfile
=> feat(build): Add git for docker image

examples/agents/react_agent_example.py, packages/dbgpt-core/src/dbgpt/agent/core/base_agent.py, packages/dbgpt-core/src/dbgpt/agent/core/role.py, packages/dbgpt-core/src/dbgpt/agent/expand/react_agent.py
ask two question，reactagent enters an infinite loop.
```python
import asyncio
import logging
import os
import sys
from typing_extensions import Annotated, Doc
from dbgpt.agent import AgentContext, AgentMemory, LLMConfig, UserProxyAgent
from dbgpt.agent.expand.actions.react_action import ReActAction, Terminate
from dbgpt.agent.expand.react_agent import ReActAgent
from dbgpt.agent.resource import ToolPack, tool
logging.basicConfig(
stream=sys.stdout,
level=logging.INFO,
format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
)
@tool
def simple_calculator(first_number: int, second_number: int, operator: str) -> float:
"""Simple calculator tool. Just support +, -, *, /.
When users need to do numerical calculations, you must use this tool to calculate, \
and you are not allowed to …
```
=> fix(agents): fix ReActAgent

configs/dbgpt-proxy-siliconflow-mysql.toml, packages/dbgpt-ext/src/dbgpt_ext/rag/embeddings/__init__.py, packages/dbgpt-ext/src/dbgpt_ext/rag/embeddings/siliconflow.py
=> feat(mode) : Adding the siliconflow embeding proxy

packages/dbgpt-core/src/dbgpt/rag/retriever/time_weighted.py, packages/dbgpt-core/src/dbgpt/storage/base.py, packages/dbgpt-core/src/dbgpt/storage/vector_store/base.py, packages/dbgpt-ext/src/dbgpt_ext/rag/assembler/embedding.py, packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/chroma_store.py, packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/elastic_store.py, packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/milvus_store.py, packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/oceanbase_store.py, packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/pgvector_store.py, packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/weaviate_store.py, packages/dbgpt-serve/src/dbgpt_serve/rag/storage_manager.py
=> fix(storage): Fix load too many chunks error

packages/dbgpt-core/pyproject.toml, packages/dbgpt-core/src/dbgpt/model/adapter/hf_adapter.py, packages/dbgpt-core/src/dbgpt/model/adapter/loader.py, pyproject.toml
Support [GLM-4-0414](https://huggingface.co/collections/THUDM/glm-4-0414-67f3cbcb34dd9d252707cb2e)
=> feat(model): Support GLM-4-0414

packages/dbgpt-ext/src/dbgpt_ext/datasource/rdbms/conn_mssql.py
add some function to mssql.
connect mssql, and use chat data or chat db test.
=> fix connect mssql embedding error

packages/dbgpt-core/src/dbgpt/agent/core/memory/hybrid.py, packages/dbgpt-core/src/dbgpt/agent/resource/tool/pack.py, packages/dbgpt-serve/src/dbgpt_serve/agent/agents/controller.py
=> fix(agent): Fix long-term memory error

packages/dbgpt-ext/pyproject.toml, packages/dbgpt-ext/src/dbgpt_ext/datasource/rdbms/conn_oracle.py, packages/dbgpt-serve/src/dbgpt_serve/datasource/manages/connector_manager.py, tests/intetration_tests/datasource/test_conn_oracle.py
oracle数据源扩展，新增service_name参数，
连接测试参考：test_conn_oracle.py，
cx_oracle包目前加入到dbgpt_ext的pyproject.toml文件中，如果依旧不对，请执行：uv pip install cx_Oracle
oracle数据源如图：
=> feat(datasource):add oracle datasource

configs/dbgpt-proxy-infiniai.toml, packages/dbgpt-core/src/dbgpt/model/proxy/__init__.py, packages/dbgpt-core/src/dbgpt/model/proxy/llms/infiniai.py, packages/dbgpt-core/src/dbgpt/rag/embedding/__init__.py, packages/dbgpt-core/src/dbgpt/rag/embedding/rerank.py
We added a new model provider, InfiniAI, which includes LLM, embedding, and rerank models.
I tried adding and deleting models in the model management and conversing with the models.
I tested the output of the embedding model and the rerank model through code.
Everything appears to be functioning normally.
```python 
import os
from dbgpt.rag.embedding import OpenAPIEmbeddings
openai_embeddings = OpenAPIEmbeddings(
api_url="https://cloud.infini-ai.com/maas/v1/embeddings",
api_key=os.getenv("INFINIAI_API_KEY"),
model_name="bge-m3",
)
texts = ["Hello, world!", "How are you?"]
res = openai_embeddings.embed_documents(texts)
print(res)
import os
from dbgpt.rag.embedding import InfiniAIRerankEmbeddings
embedding = InfiniAIRerankEmbeddings(
api_key=os.getenv("INFINIAI_API_KEY"), …
```
=> feat: add model provider InfiniAI

packages/dbgpt-serve/src/dbgpt_serve/agent/hub/plugin_hub.py
**Version: 0.7.0**
A Remote Code Execution (RCE) vulnerability exists in the plugin upload functionality through the `/v1/personal/agent/upload` endpoint. While basic security controls are in place for filename sanitization and path traversal prevention via `_sanitize_filename()`, there is no validation of the actual plugin code content. An attacker can upload a malicious Python file that passes the filename checks but contains arbitrary code. This code will be executed when the plugin is loaded through `scan_plugins()` during the `refresh_plugins()` call. The vulnerability is exploitable remotely through the FastAPI endpoint, with a clear path from user input to code execution.
The vulnerability exists in the following function call chain:
1. **Source:** `personal_agent_upload()` in …
=> [BUG] RCE Vulnerability in DB-GPT Plugin Upload System

README.ja.md, README.md, README.zh.md, configs/dbgpt-local-qwen3.example.toml, docs/blog/2025-04-29-db-gpt-qwen3-support.md, packages/dbgpt-core/pyproject.toml, packages/dbgpt-core/src/dbgpt/core/interface/media.py, packages/dbgpt-core/src/dbgpt/core/interface/message.py, packages/dbgpt-core/src/dbgpt/model/adapter/base.py, packages/dbgpt-core/src/dbgpt/model/adapter/hf_adapter.py, packages/dbgpt-core/src/dbgpt/model/cluster/worker/default_worker.py
Closes #2663 
See  `docs/blog/2025-04-29-db-gpt-qwen3-support.md`
=> feat(model): Support Qwen3 models

packages/dbgpt-core/src/dbgpt/agent/core/base_agent.py, packages/dbgpt-core/src/dbgpt/agent/core/base_team.py, packages/dbgpt-core/src/dbgpt/agent/core/memory/__init__.py, packages/dbgpt-core/src/dbgpt/agent/core/memory/agent_memory.py, packages/dbgpt-core/src/dbgpt/agent/core/role.py, packages/dbgpt-core/src/dbgpt/agent/expand/react_agent.py, packages/dbgpt-serve/src/dbgpt_serve/agent/agents/expand/app_start_assisant_agent.py
Optimizing ReAct Agent memory, supporting more complex tasks, and making multi-turn conversations more friendly.
=> feat(agent): Optimize agent memory 

packages/dbgpt-core/src/dbgpt/core/interface/llm.py, packages/dbgpt-core/src/dbgpt/model/adapter/base.py, packages/dbgpt-core/src/dbgpt/model/adapter/hf_adapter.py, packages/dbgpt-core/src/dbgpt/model/adapter/loader.py, packages/dbgpt-core/src/dbgpt/model/cluster/worker/default_worker.py, packages/dbgpt-core/src/dbgpt/model/llm/llm_out/hf_chat_llm.py, packages/dbgpt-core/src/dbgpt/model/llm/llm_out/vllm_llm.py, packages/dbgpt-core/src/dbgpt/model/llm/monkey_patch.py, packages/dbgpt-core/src/dbgpt/model/utils/hf_stream_utils.py, packages/dbgpt-core/src/dbgpt/model/utils/llm_metrics.py
- A Patch for expert parallel reasoning optimization targeting Qwen3 MOE LLM, improving inference speed by 3-5 times
- HF/vLLM inference metrics statistics, tracking and printing inference speed for each conversation (Prefill/Decode speed, etc.)
=> feat(model): Add patch for Qwen3 moe

packages/dbgpt-core/pyproject.toml
- Support llama.cpp for GLM4-z1
=> feat(model): Support llama.cpp for GLM4-z1

docs/docs/installation/integrations.md, docs/docs/installation/integrations/clickhouse_install.md, docs/docs/installation/integrations/duckdb_install.md, docs/docs/installation/integrations/mssql_install.md, docs/docs/installation/integrations/oracle_install.md, docs/docs/installation/integrations/postgres_install.md, docs/sidebars.js
Add Oracle datasource documentation examples  and update duplicate command of start webserver
=> docs(datasource): integration oracle doc

packages/dbgpt-core/pyproject.toml
upgrade pandas version to resolve timestamp formate problem
pandas issue: https://github.com/pandas-dev/pandas/issues/53686
Close #2689 
On chat_excel scene, upload file and chat with query date type column question
=> chore: upgrade pandas version

packages/dbgpt-app/src/dbgpt_app/component_configs.py, packages/dbgpt-app/src/dbgpt_app/operators/datasource.py, packages/dbgpt-app/src/dbgpt_app/operators/report.py, packages/dbgpt-core/src/dbgpt/util/pd_utils.py, packages/dbgpt-serve/src/dbgpt_serve/flow/templates/en/chat-data-awel-flow-template.json, packages/dbgpt-serve/src/dbgpt_serve/flow/templates/zh/chat-data-awel-flow-template.json, tests/intetration_tests/datasource/test_conn_oracle.py
Add a "Chat Data" AWEL flow template.
=> feat(flow): Add Chat Data template

packages/dbgpt-app/src/dbgpt_app/_version.py, packages/dbgpt-client/src/dbgpt_client/_version.py, packages/dbgpt-core/src/dbgpt/_version.py, packages/dbgpt-ext/src/dbgpt_ext/_version.py, packages/dbgpt-serve/src/dbgpt_serve/_version.py, pyproject.toml
=> chore: tag v0.7.2

configs/dbgpt-local-qwen3.example.toml, configs/dbgpt-proxy-infiniai.toml, configs/dbgpt-proxy-siliconflow-mysql.toml, configs/dbgpt-proxy-siliconflow.toml, packages/dbgpt-core/src/dbgpt/model/adapter/embed_metadata.py, packages/dbgpt-core/src/dbgpt/rag/embedding/embeddings.py, packages/dbgpt-core/src/dbgpt/rag/embedding/rerank.py, tests/intetration_tests/datasource/test_conn_starrocks.py
Support Qwen3 embeddings models and Qwen reraker models.
=> feat(model): Support Qwen3 embeddings

packages/dbgpt-core/src/dbgpt/rag/embedding/rerank.py
Fix deploy `proxy/openapi` reranker error.
=> fix(model): Fix proxy reranker bug

docs/docs/agents/modules/memory/hybrid_memory.md, docs/docs/agents/modules/memory/long_term_memory.md, docs/docs/awel/cookbook/first_rag_with_awel.md, docs/docs/awel/cookbook/write_your_chat_database.md, examples/awel/simple_nl_schema_sql_chart_example.py, examples/sdk/chat_data_with_awel.py, packages/dbgpt-core/src/dbgpt/agent/core/memory/hybrid.py
update create chromaStore param and docs
=> chore: update create chroma store param

packages/dbgpt-core/src/dbgpt/vis/tags/vis_thinking.py, packages/dbgpt-serve/src/dbgpt_serve/conversation/api/endpoints.py, packages/dbgpt-serve/src/dbgpt_serve/conversation/api/schemas.py, packages/dbgpt-serve/src/dbgpt_serve/conversation/models/models.py
- Support exporting conversation messages via API
- Fixed the display problem of mixed codes in think messages
=> feat(core): Support export messages

packages/dbgpt-serve/src/dbgpt_serve/rag/storage_manager.py
Close #2809 
add storage client cache
no need
=> feat:add storage client cache

configs/dbgpt-proxy-aimlapi.toml, docker/base/Dockerfile, docs/docs/config-reference/llm/aimlapi_aimlapideploymodelparameters_a1b2c3.mdx, docs/docs/config-reference/llm/index.mdx, docs/docs/installation/docker.md, docs/docs/installation/docker_compose.md, docs/docs/installation/integrations/aimlapi_llm_install.md, packages/dbgpt-core/src/dbgpt/model/proxy/__init__.py, packages/dbgpt-core/src/dbgpt/model/proxy/llms/aimlapi.py, packages/dbgpt-ext/src/dbgpt_ext/rag/embeddings/__init__.py, packages/dbgpt-ext/src/dbgpt_ext/rag/embeddings/aimlapi.py
Introduces support for AI/ML API as a proxy LLM and embedding provider. Adds configuration files, documentation, and implementation for AimlapiLLMClient and AimlapiEmbeddings, enabling use of 300+ models via AI/ML API. Updates Dockerfile and installation docs to guide users on enabling and configuring the new provider.
This PR adds integration with AI/ML API as a proxy-compatible LLM and embedding provider.
Key changes:
* Adds `AimlapiLLMClient` and `AimlapiEmbeddings` classes
* Registers both clients in the model adapter system
* Adds TOML configuration: `configs/dbgpt-proxy-aimlapi.toml`
* Adds documentation: usage guide, Docker instructions, config reference
* Supports OpenAI-compatible interface (`Llm.v1.gpt-3.5-turbo-1106` schema)
No breaking changes introduced. Integration is opt-in …
=> feat(model): AI/ML API integration

CONTRIBUTING.md
=> docs: update CONTRIBUTING.md to use uv package manager

packages/dbgpt-app/src/dbgpt_app/operators/datasource.py, packages/dbgpt-app/src/dbgpt_app/operators/rag.py
Fix the bug that the HO context key parameter configuration did not take effect.
=> fix(awel): Fix HO context key error

packages/dbgpt-ext/src/dbgpt_ext/datasource/rdbms/conn_doris.py, tests/intetration_tests/datasource/test_conn_doris.py
1. connection doris with Mysql protocol and  implement get_table_info method for DorisConnector
2. remove Metadata  call reflect avoid Doris type parsing error
Step1: connection Doris datasource
Step2: use ChatDB scene with Doris Resource
=> fix(datasource): fix doris DB connection use mysql protocol

packages/dbgpt-serve/src/dbgpt_serve/rag/storage_manager.py
- Enhanced error message to provide clear, actionable steps for users
- Guides users to use dedicated config file (configs/dbgpt-graphrag.toml)
- Includes docker command to start TuGraph database
- Provides example configuration for manual setup
- Similar improvements for full-text storage error message
Fixes #2880
=> fix(rag): improve graph storage configuration error message (#2880)
