pilot/configs/__init__.py
for now change .env do not work
because we change the config -> configs and in that we do not load the dotenv
this bug brings from commit https://github.com/csunny/DB-GPT/commit/4bd45747ad078808498126b67d0b0bf2a4f27f95
and I am not sure if we can delete `pilot/server/__init__.py`  we need to check.
@csunny
fix: #88
=> fix: dotenv can not load

README.md, README.zh.md, pilot/embedding_engine/loader/ppt_loader.py, scripts/setup_autodl_env.sh
=> chore: latest AutoDL image

pilot/model/cluster/worker/default_worker.py, pilot/model/cluster/worker/embedding_worker.py, pilot/model/loader.py, pilot/openapi/api_v1/api_v1.py, pilot/openapi/api_view_model.py, pilot/utils/model_utils.py
=> feat(web): Add incremental response to streaming response for `/v1/chat/completion` request

pilot/model/cluster/worker/manager.py, pilot/model/parameter.py
reason:
for openai user in China, most of us use `http_proxy` or `https_proxy` for openai things,
but for the controller_addr  load reason when have this proxy in env, the pilot can not start, so we can check if use llmproxy to ignore it
=> fix: proxyllm do not need controller_addr

.env.template, docs/getting_started/install/llm/llama/llama_cpp.md, docs/locales/zh_CN/LC_MESSAGES/getting_started/install/llm/llama/llama_cpp.po, pilot/configs/model_config.py, pilot/model/adapter.py, pilot/model/cluster/manager_base.py, pilot/model/cluster/worker/manager.py, pilot/model/cluster/worker/remote_manager.py, pilot/server/dbgpt_server.py, setup.py
Close #567 
Close #644
Close #563
**Other**
- Fix raise Exception when stop DB-GPT
=> feat(model): llama.cpp support new GGUF file format

.env.template, pilot/scene/chat_knowledge/v1/chat.py, pilot/server/knowledge/service.py, pilot/summary/db_summary_client.py, pilot/vector_store/base.py, pilot/vector_store/chroma_store.py, pilot/vector_store/milvus_store.py, pilot/vector_store/weaviate_store.py
.env other vector db customize vector store config does not work
Close #655
=> fix(ChatKnowledge):.env other vector db  customize vector store config does not work

.dockerignore, docker/base/Dockerfile, pilot/model/cluster/embedding/loader.py, pilot/model/cluster/worker/default_worker.py, pilot/model/cluster/worker/manager.py, pilot/server/dbgpt_server.py, pilot/utils/system_utils.py, pilot/utils/tracer/tracer_cli.py
**Others**
- Fix the problem of repeated startup of start ModelWorker in cluster deploying.
- Docker image use `Asia/Shanghai` as timezone when LANGUAGE is "zh"
=> feat(core): Read and save system information to tracer

pilot/scene/chat_data/chat_excel/excel_learning/prompt.py
1.Fix ChatExcel Language confusion bug
#719
=> bugfix(ChatExcel): ChatExcel Language confusion bug

README.md
I have fixed all typos and minute punctuations errors and corrected all the grammatical errors in README.md.
=> docs: corrected all grammatical errors in README.md

pilot/model/proxy/llms/tongyi.py
=> bugfix(ChatExcel): Tongyi proxyllm response with 'InvalidParameter:User and assistant need to appear alternately in the message' 

docs/getting_started/install/environment/environment.md, pilot/base_modules/agent/plugins_util.py, pilot/connections/rdbms/conn_clickhouse.py, pilot/openapi/api_v1/api_v1.py, pilot/openapi/api_v1/editor/api_editor_v1.py, pilot/openapi/api_view_model.py, pilot/openapi/base.py, pilot/scene/base_chat.py, pilot/scene/chat_dashboard/data_loader.py, pilot/scene/chat_dashboard/prompt.py, pilot/scene/chat_data/chat_excel/excel_analyze/prompt.py, pilot/scene/chat_data/chat_excel/excel_learning/prompt.py, pilot/scene/chat_db/auto_execute/prompt.py, pilot/scene/chat_db/auto_execute/prompt_baichuan.py, pilot/scene/chat_db/professional_qa/prompt.py, pilot/scene/chat_knowledge/inner_db_summary/prompt.py, pilot/scene/chat_knowledge/v1/prompt.py, pilot/scene/chat_knowledge/v1/prompt_chatglm.py, pilot/scene/chat_normal/prompt.py, pilot/server/knowledge/api.py, pilot/server/llm_manage/api.py, pilot/server/prompt/api.py
=> env param doc bugfix & typos fix

examples/awel/simple_chat_dag_example.py, examples/awel/simple_dag_example.py, examples/awel/simple_rag_example.py, pilot/awel/trigger/base.py, pilot/awel/trigger/http_trigger.py, setup.py
- Add cache dependency to `default`
=> feat(awel): Modify AWEL http trigger route function

README.md, README.zh.md, pilot/configs/model_config.py, pilot/model/base.py, pilot/model/cluster/worker/default_worker.py, pilot/utils/benchmarks/llm/fastchat_benchmarks_inference.py, pilot/utils/benchmarks/llm/llm_benchmarks.py, pilot/utils/model_utils.py, scripts/run_llm_benchmarks.sh
- Add more support model list to README.md  and `pilot/configs/model_config.py`
- Add memory usage for LLM benchmarks
- Fix benchmarks first token latency metrics bug
=> feat(model): Add more support model list and modify LLM benchmarks

assets/schema/knowledge_management.sql, pilot/base_modules/agent/db/my_plugin_db.py, pilot/configs/model_config.py, pilot/connections/manages/connect_config_db.py, pilot/memory/chat_history/base.py, pilot/memory/chat_history/chat_hisotry_factory.py, pilot/memory/chat_history/chat_history_db.py, pilot/memory/chat_history/store_type/duckdb_history.py, pilot/memory/chat_history/store_type/meta_db_history.py, pilot/openapi/api_v1/api_v1.py, pilot/openapi/api_view_model.py, pilot/scene/base_chat.py, pilot/scene/message.py, pilot/server/prompt/prompt_manage_db.py, setup.py
Closes #843 
Other:
- Support auto-gptq and autoawq, for `Yi-34B-Chat-8bits` and `Yi-34B-Chat-4bits`
=> feat(core): MTB supports multi-user and multi-system fields

pilot/model/proxy/llms/chatgpt.py
Azure Openai reponse may have an empty chunk at the first streming response, i.e. the "choices" key have an empty list.
This will cause the error from reponse json parser.
You can see the  ` "choices": []` at the first response.
Do a empty/None check before parse the response json.
=> bugfix(Azure): fix index out of range error due to Azure Openai reponses an empty chunk at first

pilot/server/knowledge/document_db.py, pilot/server/knowledge/service.py
add func get_knowledge_documents_count_bulk to instead get_knowledge_documents_count when query spaces, only query one time, not many times.
Closes #905
=> fix: optimize api /knowledge/space/list

.github/workflows/test-python.yml, dbgpt/datasource/rdbms/tests/test_conn_sqlite.py, dbgpt/model/cluster/apiserver/tests/test_api.py, requirements/dev-requirements.txt
[Here](https://github.com/fangyinc/DB-GPT/actions/runs/7261716537) is the result of this workflow on my repository.
=> ci: Add python unit test workflows

dbgpt/core/interface/message.py, dbgpt/core/interface/tests/test_message.py, dbgpt/model/proxy/llms/bard.py, dbgpt/model/proxy/llms/chatgpt.py
When there are multiple repeated user inputs in the message history, there is a bug in this piece of code.
example
history
user: hello
assistant: hi
user: hello
after remove & append:
history
assistant: hi
user: hello
user: hello
=> fix(core): Move the last user's information to the end

.env.template, docs/docs/installation/sourcecode.md
Fix wenxin config in .env.template
In dbgpt/_private/config.py, os.getenv("WEN_XIN_API_SECRET") is used to get API_SECRET.
But in .env.template WEN_XIN_SECRET_KEY is set.
Thus config.py cannot get correct API_KEY.
And PROXY_API is not needed because dbgpt/model/proxy/llms/wenxin.py automatically choose api url.
https://github.com/eosphoros-ai/DB-GPT/blob/d9065227bd61359e4ab71a499c33ace7f61520f8/dbgpt/model/proxy/llms/wenxin.py#L63-L83
Refer to issue #964
=> Fix wenxin config in .env.template

Makefile, dbgpt/core/__init__.py, dbgpt/core/awel/operator/base.py, dbgpt/core/awel/trigger/http_trigger.py, dbgpt/core/interface/llm.py, dbgpt/datasource/rdbms/base.py, dbgpt/datasource/rdbms/conn_clickhouse.py, dbgpt/datasource/rdbms/conn_sqlite.py, dbgpt/datasource/rdbms/tests/test_conn_sqlite.py, dbgpt/model/__init__.py, dbgpt/model/cluster/base.py, dbgpt/model/cluster/client.py, dbgpt/model/cluster/manager_base.py, dbgpt/model/cluster/tests/conftest.py, dbgpt/model/cluster/worker/default_worker.py, dbgpt/model/cluster/worker/embedding_worker.py, dbgpt/model/cluster/worker/manager.py, dbgpt/model/cluster/worker/remote_manager.py, dbgpt/model/cluster/worker/remote_worker.py, dbgpt/model/cluster/worker_base.py, dbgpt/model/proxy/llms/chatgpt.py, dbgpt/model/utils/chatgpt_utils.py, dbgpt/rag/summary/db_summary_client.py, examples/awel/simple_llm_client_example.py, examples/sdk/simple_sdk_llm_example.py, examples/sdk/simple_sdk_llm_sql_example.py, requirements/dev-requirements.txt, requirements/lint-requirements.txt, setup.py
- New LLMClient
- Add Makefile for test/fmt/pre-commit
- Fix SQLite unit test error
=> feat(model): Add new LLMClient and new build tools

dbgpt/model/llm_out/proxy_llm.py
fix the error of default proxyllm generator function: proxyllm_generate_stream.<locals>.<lambda>() takes 0 positional arguments but 5 were given
=> fix: default proxyllm generator function

dbgpt/model/cluster/worker/default_worker.py, dbgpt/model/cluster/worker/manager.py, dbgpt/model/proxy/llms/chatgpt.py, dbgpt/model/proxy/llms/proxy_model.py, dbgpt/model/utils/chatgpt_utils.py, dbgpt/model/utils/token_utils.py, dbgpt/serve/conversation/tests/test_models.py, dbgpt/serve/prompt/tests/test_models.py, dbgpt/serve/prompt/tests/test_service.py, dbgpt/serve/utils/_template_files/default_serve_template/tests/test_models.py, dbgpt/storage/chat_history/chat_history_db.py, dbgpt/storage/metadata/_base_dao.py, dbgpt/storage/metadata/db_manager.py, dbgpt/storage/metadata/tests/test_base_dao.py, dbgpt/storage/metadata/tests/test_db_manager.py, examples/awel/simple_llm_client_example.py
Other:
- Remove unnecessary orm operation wrapper
=> feat(model): Proxy model support count token

README.zh.md, dbgpt/_private/config.py, dbgpt/model/proxy/llms/baichuan.py, docs/docs/modules/smmf.md
Update Baichuan API to support the latest Baichuan-Turbo model and Baichuan-Turbo-192K model.
=> feat(model): Support Baichuan API

dbgpt/storage/vector_store/chroma_store.py
- Fixed the issue where vectors in the ChromaDB were not being deleted when a document was removed.
Close #1021
=> fix(ChatKnowledge): delete Chroma by vector ids did not success

dbgpt/agent/agents/expand/summary_assistant_agent.py, examples/agents/single_summary_agent_dialogue_example.py
Add summary assistant agent `DB-GPT/dbgpt/agent/agents/expand/summary_assistant_agent.py` and the example of summary assistant agent `DB-GPT/examples/agents/single_summary_agent_dialogue_example.py`. The summary assistant can generate summary according to the questions provided by user's. Currently, it only support GPT series.
Please just run `python examples/agents/single_summary_agent_dialogue_example.py`, and you will get the following result:
Yes.
=> feat(multi-agents):Add Summary Assistant Agent According to User's Question

dbgpt/rag/extractor/summary.py, dbgpt/rag/operator/db_schema.py, dbgpt/rag/operator/embedding.py, dbgpt/rag/operator/knowledge.py, dbgpt/rag/operator/rerank.py, dbgpt/rag/operator/rewrite.py, dbgpt/rag/operator/summary.py, dbgpt/rag/retriever/db_schema.py, dbgpt/rag/retriever/embedding.py, dbgpt/rag/retriever/rewrite.py, dbgpt/rag/retriever/tests/test_db_struct.py, dbgpt/rag/summary/db_summary_client.py, dbgpt/rag/text_splitter/token_splitter.py, dbgpt/serve/rag/assembler/db_schema.py, dbgpt/serve/rag/assembler/embedding.py, dbgpt/serve/rag/assembler/summary.py, dbgpt/serve/rag/assembler/tests/test_embedding_assembler.py, dbgpt/serve/rag/operators/base.py, dbgpt/serve/rag/operators/db_schema.py, dbgpt/serve/rag/operators/embedding.py, dbgpt/storage/vector_store/connector.py, examples/awel/simple_dbschema_retriever_example.py, examples/awel/simple_rag_embedding_example.py, examples/awel/simple_rag_retriever_example.py, examples/awel/simple_rag_rewrite_example.py, examples/awel/simple_rag_summary_example.py, examples/rag/db_schema_rag_example.py, examples/rag/embedding_rag_example.py
- add rag operators 
-  AssemblerOperators
-  RetrieverOperators
- KnowledgeOperator
- SummaryOperator
- RewriteOperator
- RerankOperator
- add rag awel examples
- python examples/awel/simple_rag_summary_example.py
- python examples/awel/simple_rag_rewrite_example.py
- python examples/awel/simple_rag_embedding_example.py
- python examples/awel/simple_rag_retriever_example.py
- python examples/awel/simple_dbschema_retriever_example.py
=> feat(RAG):add rag operators and rag awel examples

examples/awel/simple_dbschema_retriever_example.py, examples/awel/simple_rag_embedding_example.py, examples/awel/simple_rag_retriever_example.py
When I set the parameter EMBEDDING_MODEL=bge-large-zh, an error occurs when starting the service
2024-01-19 17:51:55 172-16-10-163 dbgpt.core.awel.dag.loader[5422] ERROR Failed to import: /mnt/data/xiuzhu/DB-GPT/examples/awel/simple_rag_retriever_example.py, error message: Traceback (most recent call last):
File "/mnt/data/xiuzhu/DB-GPT/dbgpt/core/awel/dag/loader.py", line 86, in parse
loader.exec_module(new_module)
File "", line 883, in exec_module
File "", line 241, in _call_with_frames_removed
File "/mnt/data/xiuzhu/DB-GPT/examples/awel/simple_rag_retriever_example.py", line 91, in
vector_connector = _create_vector_connector()
File "/mnt/data/xiuzhu/DB-GPT/examples/awel/simple_rag_retriever_example.py", line 86, in _create_vector_connector
).create(),
File …
=> [hotfix] Fix examples/awel default loading model text2vec-large-chinese issue

dbgpt/rag/operator/schema_linking.py, dbgpt/rag/schemalinker/base_linker.py, dbgpt/rag/schemalinker/schema_linking.py, examples/awel/simple_nl_schema_sql_chart_example.py
feat: add schemalinking awel example：nl -> schema -> sql -> chart
pre-requirements:
1. install openai python sdk
```
pip install -e ."[openai]"
```
2. set openai key and base
```
export OPENAI_API_KEY={your_openai_key}
export OPENAI_API_BASE={your_openai_base}
```
or
```
import os
os.environ["OPENAI_API_KEY"] = {your_openai_key}
os.environ["OPENAI_API_BASE"] = {your_openai_base}
```
3. run
`python examples/awel/simple_nl_schema_sql_chart_example.py`
Examples:
```shell
curl --location 'http://127.0.0.1:5555/api/v1/awel/trigger/examples/rag/schema_linking' \
--header 'Content-Type: application/json' \
--data '{"query": "Statistics of user age in the user table are based on three categories: age is less than 10, age is greater than or equal to 10 and less than or equal to 20, and age is …
```
=> feat: add schema-linking awel example

dbgpt/core/awel/dag/base.py, dbgpt/core/awel/runner/local_runner.py, dbgpt/core/awel/trigger/http_trigger.py
Other: 
- Add type annotation for `HttpTrigger`.
1. `make test`.
2. `examples/awel/simple_chat_history_example.py` can't work before this PR.
=> fix(core): Fix bug of sharing data across DAGs

dbgpt/rag/embedding/embeddings.py
I added a JinaEmbeddings class to enable the use of Jina Embeddings from their API
```python
from dbgpt.rag.embedding.embeddings import JinaEmbeddings
embs = JinaEmbeddings(api_key=<your_key>) 
ret = embs.embed_documents(['hey here', 'hey there'])
print(ret)
```
=> feat: add Jina Embeddings

dbgpt/core/interface/operators/message_operator.py, dbgpt/storage/vector_store/milvus_store.py
Close #1116
- BufferedConversationMapperOperator
- Milvus add username and password
when chat knowledge,
default setting prompt should with no history messages
=> fix:default setting prompt with history messages

dbgpt/model/utils/chatgpt_utils.py, docs/docs/installation/advanced_usage/More_proxyllms.md, docs/sidebars.js
Support Azure OpenAI Proxy
- Add API_AZURE_DEPLOYMENT environment variables to adapt to Azure openAI
- Add variables to adapter to Azure OpenAI
Added support for Azure openAI and added API_AZURE_DEPLOYMENT environment variables to adapt to Azure openAI
The test translation has been completed
=> feat(model): Add support for Azure openAI 

dbgpt/core/awel/flow/base.py, dbgpt/core/awel/trigger/http_trigger.py, dbgpt/core/interface/operators/llm_operator.py, dbgpt/rag/operators/knowledge.py, dbgpt/rag/operators/rewrite.py, dbgpt/rag/operators/summary.py, dbgpt/serve/rag/operators/knowledge_space.py, examples/awel/simple_rag_summary_example.py, examples/rag/simple_rag_embedding_example.py, examples/rag/simple_rag_retriever_example.py
add  rag awel operator view metadata.
Example1: chat knowledge
create awel  rag example as follows:
curl http test:
`
curl -X 'POST' \
'http://127.0.0.1:5000/api/v1/awel/trigger/rag/chat/completion' \
-H 'accept: application/json' \
-H 'Content-Type: application/json' \
-d '{
"model": "chatgpt_proxyllm",
"messages": "your question"
"stream": false
}'
`
Example2: document summary
create awel  rag example as follows:
curl http test:
`
curl -X 'POST' \
'http://127.0.0.1:5000/api/v1/awel/trigger/rag/summary' \
-H 'accept: application/json' \
-H 'Content-Type: application/json' \
-d '{
"model": "chatgpt_proxyllm",
"messages": "hello"
"stream": false
}'
`
=> feat:add rag awel operator view metadata.

dbgpt/_version.py, dbgpt/app/openapi/api_v1/api_v1.py, dbgpt/core/awel/flow/base.py, dbgpt/core/awel/operators/base.py, dbgpt/core/awel/operators/stream_operator.py, dbgpt/core/interface/operators/prompt_operator.py, dbgpt/serve/flow/service/service.py, dbgpt/util/dbgpts/repo.py, docs/docs/upgrade/v0.5.0.md, setup.py
Support more chat flows.
`make test`
=> feat(core): Support more chat flows

dbgpt/core/awel/runner/local_runner.py, dbgpt/serve/flow/service/service.py, dbgpt/storage/vector_store/milvus_store.py, dbgpt/util/dbgpts/cli.py, dbgpt/util/dbgpts/repo.py, dbgpt/util/function_utils.py, docs/docs/awel/cookbook/quickstart_basic_awel_workflow.md, scripts/setup_autodl_env.sh, setup.py
Support chat with RAG AWEL flow.
Other:
- AutoDL image use Qwen-1_8B-Chat as default LLM model
- `dbgpts` supports add repo with git branch argument
- Closes #1184 
`make test`
`dbgpt repo add --repo aries-ckt/dbgpts --url https://github.com/Aries-ckt/dbgpts.git`
`dbgpt app install awel-flow-rag-chat-example`
=> feat(core): Support RAG chat flow

dbgpt/app/scene/chat_data/chat_excel/excel_reader.py, dbgpt/util/pd_utils.py
Regarding these issues：
1. "can't transfor numeric column" , e.g. string column
2. all empty column in Excel
3. “I am ￥￥￥” in csv_colunm_foramt
using related excels
- [1] My code follows the style guidelines of this project
- [1 ] I have already rebased the commits and make the commit message conform to the project standard.
- [1 ] I have performed a self-review of my own code
- [ 1] I have commented my code, particularly in hard-to-understand areas
- [1 ] I have made corresponding changes to the documentation
=> Increase the accuracy of reading Excel

dbgpt/app/component_configs.py, dbgpt/app/initialization/scheduler.py, dbgpt/cli/cli_scripts.py, dbgpt/core/awel/dag/loader.py, dbgpt/core/awel/trigger/http_trigger.py, dbgpt/model/base.py, dbgpt/model/cluster/worker/manager.py, dbgpt/serve/flow/config.py, dbgpt/serve/flow/service/service.py, dbgpt/util/dbgpts/base.py, dbgpt/util/dbgpts/cli.py, dbgpt/util/dbgpts/loader.py, dbgpt/util/dbgpts/repo.py, dbgpt/util/dbgpts/template.py, setup.py
- Support dynamic loading of dbgpts
- Support install `operator` from dbgpts
- New command to create a template of dbgpts: `dbgpt new app --help`
Test dynamic loading.
1. Start your DB-GPT
2.Install an new AWEL flow, eg. `dbgpt app install awel-flow-rag-chat-example`
3. Wait 10 seconds, then reload refresh  web page and you will see the new flow.
=> feat(core): Dynamically loading dbgpts

dbgpt/core/awel/trigger/http_trigger.py
Closes #1218 
1. `python examples/awel/simple_dag_example.py`
2. `curl -X GET http://127.0.0.1:5555/api/v1/awel/trigger/examples/hello\?name\=zhangsan`
=> fix(core): Fix HTTP Trigger parse parameter bug

dbgpt/app/scene/chat_knowledge/v1/chat.py, dbgpt/core/awel/flow/__init__.py, dbgpt/core/awel/flow/base.py, dbgpt/core/awel/util/parameter_util.py, dbgpt/serve/agent/team/layout/agent_operator_resource.py, dbgpt/serve/rag/operators/knowledge_space.py
AWEL flow dynamically read optional parameter list, now supports:
- `SpaceRetrieverOperator`
- `AwelAgent`
Test it with `SpaceRetrieverOperator`.
1. Start DB-GPT
2. New AWEL flow, select `SpaceRetrieverOperator`, you can see a list of "Space Name"
3. Create a new knowledge space.
4. Reload your web page.
5. New AWEL flow, select `SpaceRetrieverOperator`, you can see a list of "Space Name" includs your new space name.
=> feat: AWEL flow supports dynamic parameters

dbgpt/model/cluster/apiserver/api.py, dbgpt/model/parameter.py, dbgpt/rag/embedding/__init__.py, dbgpt/rag/embedding/embeddings.py, dbgpt/storage/vector_store/base.py, dbgpt/storage/vector_store/connector.py, docs/docs/installation/advanced_usage/OpenAI_SDK_call.md, examples/rag/embedding_rag_example.py, examples/rag/rag_embedding_api_example.py
API Server adds embedding API compatible with [OpenAI embeddings](https://platform.openai.com/docs/api-reference/embeddings/create)
Others:
- Support load documents with multi-threadeds
- New `OpenAPIEmbeddings` 
1. Start DB-GPT's API Server according [OpenAI SDK Calls Local Multi-model
](https://docs.dbgpt.site/docs/installation/advanced_usage/OpenAI_SDK_call)
2. Test with cURL
```bash
curl http://127.0.0.1:8100/api/v1/embeddings \
-H "Authorization: Bearer EMPTY" \
-H "Content-Type: application/json" \
-d '{
"model": "text2vec",
"input": "Hello world!"
}'
```
```python
from dbgpt.rag.embedding import OpenAPIEmbeddings
openai_embeddings = OpenAPIEmbeddings(
api_url="http://localhost:8100/api/v1/embeddings",
api_key="EMPTY",
model_name="text2vec",
)
texts = ["Hello, world!", "How are …
```
=> feat: APIServer supports embeddings

dbgpt/core/awel/task/base.py, dbgpt/core/awel/task/task_impl.py
Closes #1310
`python examples/sdk/simple_sdk_llm_sql_example.py `
=> fix(awel): Fix awel check empty data bug

setup.py
Install py-pg use `psycopg2-binary` instead of `psycopg2`
```
pip install psycopg2-binary
```
=> fix: pg py dependency problem

dbgpt/app/initialization/serve_initialization.py, dbgpt/app/openapi/api_v2.py, dbgpt/client/datasource.py, dbgpt/client/schema.py, dbgpt/datasource/manages/connect_config_db.py, dbgpt/serve/datasource/api/endpoints.py, dbgpt/serve/datasource/api/schemas.py, dbgpt/serve/datasource/config.py, dbgpt/serve/datasource/dependencies.py, dbgpt/serve/datasource/serve.py, dbgpt/serve/datasource/service/service.py, docs/docs/api/app.md, docs/docs/api/datasource.md, docs/docs/api/flow.md, docs/sidebars.js, examples/client/datasource_crud_example.py, examples/client/flow_crud_example.py
Close #1328
1. Add datasource api v2
2. Client Support chatdata
3. Add examples and docs
1.`python dbgpt/app/dbgpt_server.py`
2. add  datasource called `dbgpt`
```
DBGPT_API_KEY=dbgpt
curl -X POST "http://localhost:5000/api/v2/chat/completions" \
-H "Authorization: Bearer $DBGPT_API_KEY" \
-H "accept: application/json" \
-H "Content-Type: application/json" \
-d "{\"messages\":\"show spaces data limit 5\",\"model\":\"chatgpt_proxyllm\",\"chat_mode\":\"chat_data\",\"chat_param\":\"dbgpt\",\"stream\":false}"
```
```json
{
"id": "2bb80fdd-e47e-4083-8bc9-7ca66ee0931b",
"object": "chat.completion",
"created": 1711509733,
"model": "chatgpt_proxyllm",
"choices": [
{
"index": 0,
"message": {
"role": "assistant",
"content": "The user wants to display information about knowledge spaces with a limit …
```
=> feat: Client support chatdata

dbgpt/_private/config.py, dbgpt/app/base.py, dbgpt/app/dbgpt_server.py
The modification in the. evn file to WEB-SERVER-PORT is currently invalid. Please fix this issue now.
=> fix: Fix the issue of invalid port settings

dbgpt/storage/vector_store/milvus_store.py
set VECTOR_STORE_TYPE=Milvus
When delete knowledge, error: space list error embedding is required for MilvusStore. 
1. set VECTOR_STORE_TYPE=Milvus
2. delete knowledge
=> fix: when delete knowledge, error: space list error embedding is required for MilvusStore

setup.py
Fixed the issue where some users were unable to install dependencies properly using `pip install -e ".[default]"`, and updated some dependencies to be installed via the PyPI channel.
If users wish to complete the usage of the quantitative library, they should execute `pip install -e ".[bitsandbytes]"`, but please ensure that it is done under conditions where network connectivity is supported.
`pip install -e ".[default]"`
Here is the successful screenshot of executing `pip install -e ".[default]"`:
Here is the successful screenshot of executing `pip install -e ".[bitsandbytes]"`:
=> fix: Fix the default dependency installation error

.github/workflows/pylint.yml, dbgpt/app/knowledge/service.py, dbgpt/storage/vector_store/milvus_store.py
This PR attempts to fix the 'make mymp' error outlined in CONTRIBUTING.md that was introduced by PR #1359, particularly when submitting new PRs. Due to the lack of a Milvus environment on my end, I would kindly ask for testing before merging to ensure the issue with PR #1359 has been resolved. Apologies for the inconvenience.
`make fmt`
`make test`
`make mypy`
Due to working on an internal network, I cannot submit screenshots. Please proceed with direct testing.
=> fix:  Fix the mypy check error

dbgpt/app/openapi/api_v1/editor/api_editor_v1.py, dbgpt/app/scene/chat_dashboard/data_loader.py, dbgpt/util/date_utils.py
Close #1264
Fix Dashboard Editor run error.
=> fix: dashboard editor run error 

dbgpt/cli/cli_scripts.py, dbgpt/core/awel/flow/base.py, dbgpt/core/awel/flow/flow_factory.py, dbgpt/core/awel/trigger/ext_http_trigger.py, dbgpt/core/awel/trigger/http_trigger.py, dbgpt/util/network/_cli.py
- New HTTP sender operator.
- New network command for debugging. DB-GPT not support global proxy for [#616](https://github.com/eosphoros-ai/DB-GPT/pull/616#issuecomment-1732786465). Here is a solution to the problem via port forwarding + proxy.
1. `make test`
2. Test forward.
```bash
dbgpt net forward --local-port 5010 \
--remote-host api.openai.com \
--remote-port 443 \
--ssl \
--proxies http://127.0.0.1:7890 \
--timeout 30 
```
Then connect to it.
```bash
export OPENAI_API_BASE=http://127.0.0.1:5010/v1
curl $OPENAI_API_BASE/chat/completions \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $OPENAI_API_KEY" \
-d '{
"model": "gpt-3.5-turbo",
"messages": [
{
"role": "system",
"content": "You are a helpful assistant."
},
{
"role": "user",
"content": "hello"
}
],
"stream": …
```
=> feat: Support HTTP sender

docker/base/Dockerfile, docker/base/build_image.sh, setup.py
Upgrade torch to torch 2.2.1 and fix the issue where the installation of llama_cpp with a too high CUDA version fails.
And closes #1376
`pip install -e ".[default]"`
`pip install -e ".[llama_cpp]"`
=> feat: Upgrade torch version to 2.2.1 

web/components/app/resource-card.tsx
…r app editing
Resolve the issue of incorrect parameter echo for resources under app editing；
When editing the resource parameters of an app, randomly select a resource type and set the resource parameters, then click save; Click edit again to open, the resource parameters echoed are not saved resource parameters
1. open an app, then add one resource and set resource parameters.
2. Open the app again and view the resource parameters that were set and saved in the previous step. Instead, select the first value from the drop-down list as a display.
=> fix: Resolve the issue of incorrect parameter echo for resources under app editing

dbgpt/rag/knowledge/base.py, dbgpt/rag/knowledge/csv.py, dbgpt/rag/knowledge/datasource.py, dbgpt/rag/knowledge/docx.py, dbgpt/rag/knowledge/factory.py, dbgpt/rag/knowledge/html.py, dbgpt/rag/knowledge/markdown.py, dbgpt/rag/knowledge/pdf.py, dbgpt/rag/knowledge/pptx.py, dbgpt/rag/knowledge/string.py, dbgpt/rag/knowledge/txt.py, dbgpt/rag/knowledge/url.py, dbgpt/rag/retriever/base.py, dbgpt/rag/retriever/db_schema.py, dbgpt/rag/retriever/embedding.py, dbgpt/rag/retriever/tests/test_embedding.py, dbgpt/rag/text_splitter/text_splitter.py, dbgpt/serve/rag/retriever/knowledge_space.py, dbgpt/storage/vector_store/base.py, dbgpt/storage/vector_store/chroma_store.py, dbgpt/storage/vector_store/connector.py, dbgpt/storage/vector_store/filters.py, dbgpt/storage/vector_store/milvus_store.py, dbgpt/storage/vector_store/pgvector_store.py, dbgpt/storage/vector_store/weaviate_store.py, examples/rag/metadata_filter_example.py
Close #1387
- Add Metadata Properties Filters for VectorStore
```python
metadata_filter = MetadataFilter(key="Header2", value="AWEL Design")
filters = MetadataFilters(filters=[metadata_filter])
chunks = await retriever.aretrieve_with_scores(
"what is awel talk about", 0.0, filters
)
```
`python examples/rag/metadata_filter_example.py`
=> feat(RAG):add metadata properties filters

dbgpt/agent/__init__.py, dbgpt/agent/core/agent_manage.py, dbgpt/agent/core/base_agent.py, dbgpt/agent/plan/awel/agent_operator.py, dbgpt/agent/plan/awel/agent_operator_resource.py, dbgpt/app/component_configs.py, dbgpt/component.py, dbgpt/serve/agent/agents/controller.py, dbgpt/serve/agent/app/controller.py, dbgpt/util/dbgpts/loader.py, dbgpt/util/dbgpts/repo.py, dbgpt/util/dbgpts/template.py
Support install agent from [dbgpts](https://github.com/eosphoros-ai/dbgpts)
Restart your DB-GPT.
```bash
dbgpt repo add --repo fangyinc/dbgpts --url https://github.com/fangyinc/dbgpts.git -b agents-support
pip install poetry
dbgpt app list-remote -U
dbgpt app install summarizer-agent-example
```
Create a APP.
**Failure case**
=> feat(agent): dbgpts support agent

.env.template, dbgpt/_private/config.py, dbgpt/app/scene/base_chat.py, dbgpt/app/scene/chat_db/auto_execute/out_parser.py, dbgpt/app/scene/exceptions.py, dbgpt/util/retry.py
In some scenarios, we need to call the LLM in parallel, select the successful result, or retry in case of failure.
1. Modify `.env`
```bash
DBGPT_APP_SCENE_NON_STREAMING_RETRIES_BASE=2
DBGPT_APP_SCENE_NON_STREAMING_PARALLELISM_BASE=2
```
2. Restart DB-GPT
3. Use "Chat Data" to perform some error-prone problems, and you will find that the success rate increases.
=> feat: Support retry for 'Chat Data'

dbgpt/_private/config.py, dbgpt/rag/text_splitter/tests/test_splitters.py, dbgpt/rag/text_splitter/text_splitter.py, dbgpt/storage/vector_store/__init__.py, dbgpt/storage/vector_store/oceanbase_store.py, docker/allinone/Dockerfile, docker/compose_examples/dbgpt-oceanbase-docker-compose.yml, docs/docs/application/advanced_tutorial/rag.md, docs/docs/faq/kbqa.md, i18n/locales/zh_CN/LC_MESSAGES/dbgpt_storage.po
- feat: `OceanBase` can be used as vector store in `knowledge base` and `AWEL workflow`.
- fix: `MarkdownHeaderTextSplitter` incorrectly parses into a Markdown Header when parsing a code block containing "#" comments.
- opt: Replace subtitle metadata from JSON format to natural language in `MarkdownHeaderTextSplitter`.
Test the knowledge base function using OceanBase + DB-GPT.
`OceanBase Vector Store` Docker image can be pulled via the following command:
```shell
docker run -p 2881:2881 --name obvec -d oceanbase/oceanbase-ce:vector
```
For more information about OceanBase configuration, please view `docs/docs/faq/kbqa.md`
=> support oceanbase as an optional vector database

dbgpt/rag/evaluation/retriever.py, dbgpt/storage/vector_store/oceanbase_store.py
When using OceanBase as the Vector Store for `ChatData`, the db_profile table is not created because the vector_name_exists API returns True.
- Test the `ChatData` function using OceanBase + DB-GPT
=> fix: Fix oceanbase vector_name_exists bug

dbgpt/storage/vector_store/milvus_store.py
Fix parameter type mismatch issue when using Milvus
=> fix: Fix parameter type mismatch issue when using Milvus

.mypy.ini, dbgpt/configs/model_config.py, dbgpt/model/adapter/embeddings_loader.py, dbgpt/model/adapter/proxy_adapter.py, dbgpt/model/parameter.py, dbgpt/model/proxy/__init__.py, dbgpt/model/proxy/llms/ollama.py, dbgpt/rag/embedding/__init__.py, dbgpt/rag/embedding/embeddings.py, setup.py
Support [Ollama](https://github.com/ollama/ollama) as an optional LLM and Embedding proxy via lib [ollama-python](https://github.com/ollama/ollama-python)
Use Ollama Proxy LLM by modifying the following `.env` configurations:
```shell
LLM_MODEL=ollama_proxyllm
MODEL_SERVER=http://127.0.0.1:11434
PROXYLLM_BACKEND=llama3:instruct
```
Use Ollama Proxy Embedding by modifying the following `.env` configurations:
```shell
EMBEDDING_MODEL=proxy_ollama
proxy_ollama_proxy_server_url=http://127.0.0.1:11434
proxy_ollama_proxy_backend=llama3:instruct
```
- Simple Chat.
- Chat Data.
- Knowledge Base.
=> feat(model): support ollama as an optional llm & embedding proxy

dbgpt/serve/agent/app/controller.py, dbgpt/serve/agent/db/gpts_app.py
Closes #1464 
Use APP in web page.
=> fix: Fix app pydantic error

.env.template, README.zh.md, dbgpt/_private/config.py, dbgpt/configs/model_config.py, dbgpt/model/adapter/proxy_adapter.py, dbgpt/model/proxy/__init__.py, dbgpt/model/proxy/llms/deepseek.py
Support [Deepseek proxy LLM](https://platform.deepseek.com/api-docs/)
Closes #1490 
1. Use deepseek in DB-GPT
```bash
LLM_MODEL=deepseek_proxyllm
DEEPSEEK_MODEL_VERSION=deepseek-chat
DEEPSEEK_API_BASE=https://api.deepseek.com/v1
DEEPSEEK_API_KEY={your-deepseek-api-key}
```
Then restart DB-GPT to use it in the web page.
2. Use `DeepseekLLMClient` in python code.
Create python file `test_proxyllm.py`
```python
import asyncio
from dbgpt.model.proxy import DeepseekLLMClient
client = DeepseekLLMClient()
print(asyncio.run(client.generate(ModelRequest._build("deepseek-chat", "你是谁？"))))
```
Run `test_proxyllm.py`
```bash
DEEPSEEK_API_KEY={your-deepseek-api-key} python test_proxyllm.py
```
The output like this:
```
ModelOutput(text=' …
```
=> feat(model): Support DeepSeek proxy LLM

dbgpt/rag/retriever/embedding.py
The EmbeddingRetriever's _aretrieve_with_score and _aretrieve methods do not pass the query parameter to the rank function when calling the ranker to re-rank the retrieval results.
1. initialize a EmbeddingRetiever with the CrossEncoderRanker
`retriever = EmbeddingRetriever( vector_store_connector=vector_store_connector, top_k=100, rerank=CrossEncoderRanker(topk=3), )`
2. call aretrieve_with_scores
`retriever.aretrieve_with_scores("what is awel talk about", 0.3)`
3. debug at "[/DB-GPT/dbgpt/rag/retriever/rerank.py](https://github.com/eosphoros-ai/DB-GPT/issues/url)", line 211
4. check whether the value of parameter query is None, if not, bug is fixed.
Closes #1498
=> fix(rag): Fix rerank bug of EmbeddingRetriever

dbgpt/rag/retriever/rerank.py, dbgpt/storage/vector_store/chroma_store.py, dbgpt/storage/vector_store/pgvector_store.py
When using EmbeddingRetriever with reranking specified as CrossEncoderRanker, a TypeError ('Object of type float32 is not JSON serializable') occurs when attempting to serialize references of the answer.
=> fix(rag): Fix CrossEncoderRanker bug of EmbeddingRetriever

dbgpt/storage/vector_store/chroma_store.py, docker/base/Dockerfile
Old zh_core_web_sm model will install pydantic 1.x, we should upgrade i to new version.
Modify `.env`:
```
LANGUAGE=zh
```
Load documents into knowledge space,  then test it's  functionality.
=> fix: Upgrade spacy model

dbgpt/_version.py, dbgpt/app/knowledge/service.py, dbgpt/storage/vector_store/base.py, dbgpt/storage/vector_store/chroma_store.py, dbgpt/storage/vector_store/pgvector_store.py, setup.py
Close #1503 
- chroma store refactor
- fix issue #1503
`python examples/rag/embedding_rag_example.py`
=> feat:chroma store refactor

.env.template, dbgpt/_private/config.py, dbgpt/agent/expand/resources/host_tool.py, dbgpt/app/base.py, dbgpt/app/component_configs.py, dbgpt/app/dbgpt_server.py, dbgpt/app/initialization/embedding_component.py, dbgpt/app/scene/chat_knowledge/v1/chat.py, dbgpt/configs/model_config.py, dbgpt/core/__init__.py, dbgpt/core/interface/embeddings.py, dbgpt/core/schema/api.py, dbgpt/model/adapter/embeddings_loader.py, dbgpt/model/adapter/model_adapter.py, dbgpt/model/cluster/apiserver/api.py, dbgpt/model/cluster/base.py, dbgpt/model/cluster/embedding/remote_embedding.py, dbgpt/model/cluster/worker/embedding_worker.py, dbgpt/model/cluster/worker/manager.py, dbgpt/model/parameter.py, dbgpt/rag/embedding/__init__.py, dbgpt/rag/embedding/embedding_factory.py, dbgpt/rag/embedding/embeddings.py, dbgpt/rag/embedding/rerank.py, dbgpt/rag/retriever/embedding.py, dbgpt/rag/retriever/rerank.py, docs/docs/installation/advanced_usage/OpenAI_SDK_call.md, docs/docs/installation/model_service/cluster.md, requirements/lint-requirements.txt
DB-GPT now supports deploying rerank models in SMMF, also supports deploying in standalone mode.
1. Download the rerank model and put it in the `models` directory.
Here we take the `bge-reranker-base` model as an example.
```shell
cd DB-GPT/models
git clone https://huggingface.co/BAAI/bge-reranker-base
```
2. Modify `.env` file, just like the following:
```shell
RERANK_MODEL=bge-reranker-base
RERANK_TOP_K=3
```
3. Restart the DB-GPT webserver.
4. Use `Chat Knowledge` to test the rerank model.
If we start a rerank model, it will automatically use the rerank model to rerank the 
results after retrieving the results from the vector store.
1. Download the rerank model and put it in the `models` directory.
Here we take the `bge-reranker-base` model as an example.
```shell
cd DB-GPT/models
git …
```
=> feat(model): Support deploy rerank model

dbgpt/storage/vector_store/connector.py
delete datasource bug
delete datasource
=> fix: delete datasource bug

dbgpt/app/scene/chat_dashboard/data_loader.py
fix always use the first column as row Name+handle value None and no data
We cannot use try Catch to ignore the ERROR.
To organize the data for data dashboard. To just regard the first column as name is pretty rude. I find a method that will meet no errors(while the sql get from GPT is right). It can handle if there are no data in mysql database or there are all None data in mysql database.
Even the data in the mysql database is None is still ok. 
=> Fix data dashboard - data_loader.py

dbgpt/agent/core/plan/planner_agent.py, dbgpt/serve/agent/agents/controller.py
Remove unnecessary resources of planner agent.
In automatic planning scenarios containing`ToolAssistantAgent`, additional resources will affect the planner agent.
```bash
make test
```
=> fix(agent): Remove resources of planner agent

dbgpt/rag/assembler/bm25.py, dbgpt/rag/retriever/bm25.py, examples/rag/bm25_retriever_example.py
Close #1577 
Add Elasticsearch BM25Retriever.
https://www.elastic.co/guide/en/elasticsearch/reference/8.13/index-modules-similarity.html
1. install Elasticsearch refer https://www.elastic.co/guide/en/elasticsearch/reference/8.13/setup.html
2. update Elasticsearch config
```python
def _create_es_config():
"""create Elasticsearch config."""
return ElasticsearchVectorConfig(
name="bm25_es_dbgpt",
uri="localhost",
port="9200",
user="elastic",
password="dbgpt",
)
```
3. run example 
```bash
python examples/rag/bm25_retriever_example.py
```
=> feat(RAG): add BM25 Retriever.

dbgpt/app/scene/chat_dashboard/data_loader.py
Based on Further Test scenario:
1. ID could be int data Type(but it is the pri of row data).
2. value for <ValueItem> not support for date time or timestamp.
I personally use a lot of strange database to test the dashboard. i attached the DCL of my database. you can use this to  test it or use your database to test it.  
[sql.txt](https://github.com/eosphoros-ai/DB-GPT/files/15464499/sql.txt)
=> Update data_loader.py - timestamp+id

dbgpt/model/proxy/llms/zhipu.py
close #1536
update-zhipuai-SDK
```
LLM_MODEL=zhipu_proxyllm
PROXY_SERVER_URL=https://open.bigmodel.cn/api/paas/v4/chat/completions
ZHIPU_MODEL_VERSION=glm-4
ZHIPU_PROXY_API_KEY=xxx
```
=> feat(model): Support new zhipuai SDK

README.ja.md, README.md, README.zh.md, dbgpt/configs/model_config.py, dbgpt/model/adapter/hf_adapter.py
Support [glm-4-9b-chat](https://huggingface.co/THUDM/glm-4-9b-chat)
```bash
LLM_MODEL=glm-4-9b-chat
```
Then restart your DB-GPT server.
=> feat(model): Support glm-4-9b-chat

web/components/chart/autoChart/advisor/pipeline.ts, web/components/chart/autoChart/charts/multi-line-chart.ts, web/components/chart/autoChart/charts/multi-measure-line-chart.ts, web/components/chart/autoChart/charts/util.ts, web/components/chart/autoChart/index.tsx
The lines were connected according to the original order of the data. When the data was not arranged in chronological order, the lines were tangled in the line chart. This PR is to fix the issue by sorting the data by time when drawing the line chart 
before:
after:
=> fix(web): sort line chart data according to time order

dbgpt/model/proxy/llms/moonshot.py, dbgpt/rag/knowledge/url.py
1. moonshot proxy api port call fails because the returned object is a Stream and can't be awaited. 
2. The knowledge base loads below URL will be garbled
https://mp.weixin.qq.com/s?__biz=MzU3MjE2MzY4OA==&mid=2247488988&idx=1&sn=2f0863dd2f1598b6341f7576697e379f&chksm=fcd446dbcba3cfcd017d8053cb1a83b7525e4c0940f71751ad50a577f858f450047683529c3f&scene=27
1. After
2. After
=> fix(model): Stream object can't use await

web/components/chat/chat-content/config.tsx
chat-data等场景以表格形式展示时，会存在表格宽度超过页面宽度的情况，此前的代码逻辑中未对该情况进行适配，导致表格显示不全，因此修改部分前端样式以修复该情况，当表格宽度溢出时会自动添加滚动条，可进行左右滑动，可解决表格显示不全的问题
启动修改后的前端代码和后端代码，创建测试数据库，利用chat-data场景查询一张宽表，结果符合预期。由于改动非常简单，并无特殊测试配置
=> bugfix:fix table scroll bug

dbgpt/serve/rag/models/models.py
Missing `context` attribute prevents knowledge base configuration from taking effect.
=> fix(chat knowledge): add missing context property

web/components/chart/autoChart/charts/multi-line-chart.ts, web/components/chart/autoChart/charts/multi-measure-line-chart.ts, web/components/chart/autoChart/charts/util.ts, web/components/chart/autoChart/index.tsx
1. Previously, the line chart required the x-axis field to be of  string type, which caused the chart to fail in cases where there was no string type field. Now, if there is no string type field, the first field will be used as the x-axis.
2.add tooltip title for pie chart
=> fix(web): fix line chart using interval field as xAxis & fix pie chart tooltip

README.ja.md, README.md, README.zh.md, dbgpt/agent/expand/resources/search_tool.py, dbgpt/configs/model_config.py, dbgpt/model/adapter/hf_adapter.py, docs/blog/2024-07-24-db-gpt-llama-3.1-support.md, docs/blog/authors.yml, docs/blog/tags.yml, docs/docusaurus.config.js
Support [Llama3.1 models](https://huggingface.co/collections/meta-llama/llama-31-669fc079a0c406a149a5738f)
We assume that your models are stored in the `models` directory, e.g., `models/Meta-Llama-3.1-8B-Instruct`.
Then modify your `.env` file:
```env
LLM_MODEL=meta-llama-3.1-8b-instruct
```
Then you can run the following command to start the server:
```bash
dbgpt start webserver
```
=> feat(model): Support llama3.1 models

dbgpt/app/knowledge/_cli/knowledge_client.py, dbgpt/app/knowledge/request/request.py, dbgpt/serve/rag/service/service.py
=> fix(ChatKnowledge): Fix knowledge command load bug

dbgpt/model/proxy/llms/chatgpt.py
Fixed an issue where the Azure GPT-4o API's asynchronous responses contained empty choices arrays, leading to incorrect handling of empty data.
This is my configuration.
```
LOCAL_DB_HOST=mysql
LOCAL_DB_PASSWORD=******
ALLOWLISTED_PLUGINS=db_dashboard
LLM_MODEL=proxyllm
PROXY_API_KEY=*
PROXY_API_BASE=https://*.openai.azure.com/
PROXY_API_TYPE=azure
PROXY_SERVER_URL=https://*.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2024-02-15-preview
PROXY_API_VERSION=2024-02-15-preview
PROXYLLM_BACKEND=gpt-4o
```
When I successfully deploy with docker or a local conda environment, no matter what questions are raised on the front end, the output will be disconnected at the end and an exception will be thrown.As follows:
> Logs:
```
messages:
[{'role': 'system', 'content': …
```
=> fix(chatgpt): Resolve async response issue with Azure GPT-4o API

dbgpt/client/schema.py
Closes #1783
Fix space id error type. Id type should be int not str
=> fix: Fix knowledge api report error when call create space api

dbgpt/storage/vector_store/milvus_store.py
Close issue #1785 
fix issue1785
set .env `VECTOR_STORE_TYPE=Milvus`
=> fix: Fix can't read the milvus url config

dbgpt/app/scene/chat_knowledge/v1/chat.py, dbgpt/serve/rag/retriever/knowledge_space.py, dbgpt/serve/rag/retriever/retriever_chain.py
graph retrieve `no relevant chunks`
Chat with `KnowledgeGraph`
=> fix:graph retrieve bug

web/components/chat/db-editor.tsx
Closes #1668
fix issue1688
1. On the New Chat page
2. Select "Chat Data"
3. Interacting with the database
4. Click the "Editor" button at the top of the page
5. Manually update SQL
6. Click the Run button
=> fix(ChatData): Fix execution failure error after manually updating SQL

.env.template, dbgpt/configs/model_config.py, dbgpt/model/adapter/embeddings_loader.py, dbgpt/model/parameter.py, dbgpt/rag/embedding/__init__.py, dbgpt/rag/embedding/embeddings.py, setup.py
- Support qianfan embedding
- Fix missing proxy_tongyi_proxy_api_key={your-api-key}
- update qianfan pip whl
Test passed
- [ √] My code follows the style guidelines of this project
- [ √] I have already rebased the commits and make the commit message conform to the project standard.
- [ √]  I have performed a self-review of my own code
- [ √]  I have commented my code, particularly in hard-to-understand areas
- [ √]  Any dependent changes have been merged and published in downstream modules
=> feat(model): Support qianfan embedding and resolves an issue

dbgpt/datasource/rdbms/conn_postgresql.py
当使用postgresql数据库时，当读取表的字段较多时，这时使用sqlalchemy读取后并转为字符串后，会出现中间部分字段被”characters truncated“现象。debug查看变量发现，所有字段是都在的，只不过在加入大模型的prompt模板时，自动的toString功能会自动进行truncated。改问题记录在 [1426](https://github.com/eosphoros-ai/DB-GPT/issues/1426)
使用postgresql数据库，并设计一个超过30个字段的表，且每个字段名称的长度约大于10个字符。这时，如果在chat dashboard时，生成的prompt中会发现有中间部分的字段名称被”characters truncated“了。更新本代码后，问题解决。
=> fix: postgresql read schema_info with characters truncated if too long

dbgpt/storage/full_text/base.py, dbgpt/storage/vector_store/base.py
Close #1990 
full text storage truncate method error.
chat knowledge with full text
=> fix(ChatKnowledge):full text storage truncate method error.

docs/Dockerfile-deploy.dockerignore
Fix build doc image error.
```bash
NPM_REGISTRY=https://registry.npmmirror.com
docker build -f docs/Dockerfile-deploy \
-t eosphorosai/dbgpt-docs \
--build-arg NPM_REGISTRY=$NPM_REGISTRY \
--build-arg CI=false \
--build-arg NUM_VERSION=2 .
```
=> fix(docs): Fix build doc image error

dbgpt/rag/embedding/embeddings.py
https://github.com/eosphoros-ai/DB-GPT/issues/1748 
qwen online embedding models must not be larger than 25 
{"status_code": 400, "request_id": "cabd7ddb-386c- 9a25-a488-94fb05b4f8b8", "code": "InvalidParameter", "message": "batch size is invalid, it should not be larger than 25.: payload.input.contents", "output": null, "usage": null}
data   streaming processing
Use tongyi embedding: text-embedding-v1
Start DB-GPT and pass in the pdf file for parsing
=> fix bug - Tongyiproxy embedding model error

README.ja.md, README.md, README.zh.md, dbgpt/configs/model_config.py, dbgpt/model/adapter/hf_adapter.py
Closes #2026 
First, download the model according to [the link](https://huggingface.co/Qwen/Qwen2.5-7B-Instruct) to the models directory of the project.
Then, modify your .env file
```bash
LLM_MODEL=qwen2.5-7b-instruct
```
Finally, restart the DB-GPT.
=> feat(model): Support Qwen2.5 models

demo.py
Fix the default parameter configuration error when starting the `vllm` inference framework
[Bug]vllm error，ValueError: mutable default <class 'list'> for field ignore_patterns is not allowed: use default_factory
=> fix(model): Fix  vllm inference error

assets/schema/dbgpt.sql
When I chat with a large database, the LLM will response a large content. The pymysql will feedback this error message: Data too long for column 'message_detail' at row 1.
This PR change the type of message_detail from text to longtext. 
Reproduct that case I wrote before, the bug has been fix.
=> fix: Fix long message response error

dbgpt/rag/knowledge/docx.py
When uploading a doc file to the knowledge base, docx will occur an error when loading a file with a specific format. The reason is that docx does not parse the file element correctly and returns a null value.
The error message is :
> 2024-10-12 15:00:56 | ERROR | dbgpt.serve.rag.service.service | document embedding, failed:海外市场相关研究-补充材料.docx, "There is no item named 'NULL' in the archive"
sample file:
[海外市场相关研究-补充材料.docx](https://github.com/user-attachments/files/17349141/-.docx)
sample code:
```python
import docx
from docx.document import Document
doc = docx.Document('/Users/zhaoyu/Desktop/海外市场相关研究-补充材料.docx')
```
[This problem has been solved in the docx issues on the git](https://github.com/python-openxml/python-docx/issues/1105)
We just need to rewrite the load_from_xml_v2 method, …
=> Fixed the error caused by file format when docx loading files

dbgpt/core/interface/llm.py, dbgpt/model/cluster/apiserver/api.py, dbgpt/model/cluster/base.py, dbgpt/model/parameter.py, dbgpt/model/proxy/llms/chatgpt.py, dbgpt/model/proxy/llms/deepseek.py, dbgpt/model/proxy/llms/gemini.py, dbgpt/model/proxy/llms/moonshot.py, dbgpt/model/proxy/llms/spark.py, dbgpt/model/proxy/llms/tongyi.py, dbgpt/model/proxy/llms/yi.py, dbgpt/model/proxy/llms/zhipu.py, dbgpt/rag/knowledge/docx.py
Passing stop parameter to proxyllm
Chat with all proxy LLMs.
=> feat(model): Passing stop parameter to proxyllm

dbgpt/_private/config.py, dbgpt/storage/vector_store/oceanbase_store.py, docker/compose_examples/dbgpt-oceanbase-docker-compose.yml, docs/docs/application/advanced_tutorial/rag.md, docs/docs/faq/kbqa.md
OceanBase officially released the vector store function in version 4.3.3. The SQL statements to use vector index have been changed. For compatibility, the implementation of OceanBaseStore should be updated:
- Using [pyobvector](https://github.com/oceanbase/pyobvector) as middleware
- Support filters when perform ANN search
- Test the knowledge base function using OceanBase + DB-GPT.
- make fmt
- make mypy
- make test
=> Update OceanBaseStore to be compatible with oceanbase-4.3.3.0

dbgpt/agent/core/action/base.py, dbgpt/agent/core/memory/gpts/default_gpts_memory.py, dbgpt/agent/core/plan/awel/agent_operator_resource.py
Changes:
1. method `parse_obj` is deprecated, use `model_validate` instead.
2. remove meaningless f-string format.
3. add missing classmethod decorator.
=> fix: replace deprecated method and add missing decorator

dbgpt/serve/dbgpts/hub/models/models.py, dbgpt/serve/dbgpts/hub/service/service.py, dbgpt/storage/metadata/_base_dao.py
When I search for keywords in the DBGPTS community, I would prefer to use fuzzy matching to find relevant content. But now, I can only perform an exact match for the entire keyword.
- make fmt
- make mypy
- make test
It's better to match '%flow%' for all dbgpts, rather than only the dbgpt named 'flow'.
=> Use fuzzy matching when searching dbgpts

.env.template, dbgpt/rag/transformer/base.py, dbgpt/rag/transformer/graph_extractor.py, dbgpt/rag/transformer/llm_extractor.py, dbgpt/rag/transformer/triplet_extractor.py, dbgpt/storage/graph_store/base.py, dbgpt/storage/graph_store/tugraph_store.py, dbgpt/storage/knowledge_graph/community/tugraph_store_adapter.py, dbgpt/storage/knowledge_graph/community_summary.py, docs/docs/cookbook/rag/graph_rag_app_develop.md
It calls the async function to accelerate the process of triplets extraction from the chunk text. The config can be set in the `.env` `TRIPLET_EXTRACTION_BATCH_SIZE` (default to 20).
I have run the app server by set the value of TRIPLET_EXTRACTION_BATCH_SIZE differently. (1, 5, 100), and the running time varies.
``` python
batch_size = self._triplet_extraction_batch_size
for i in range(0, len(chunks), batch_size):
batch_chunks = chunks[i : i + batch_size]
extraction_tasks = [
self._graph_extractor.extract(chunk.content) for chunk in batch_chunks
]
async_graphs: List[List[MemoryGraph]] = await asyncio.gather(
*extraction_tasks
)
for chunk, graphs in zip(batch_chunks, async_graphs):
for graph in graphs:
if document_graph_enabled:
for edge in graph.edges():
edge.set_prop("_chunk_id", …
```
=> feat: Enhance the triplets extraction in the knowledge graph by the batch size

dbgpt/storage/vector_store/milvus_store.py
Previously, the search topk in Milvus storage was always fixed at 4. This commit fixes the issue by allowing users to specify topk dynamically.
When the parameter `VECTOR_STORE_TYPE` is set to `Milvus`, the `KNOWLEDGE_SEARCH_TOP_SIZE` parameter becomes ineffective, and the system can only match up to 4 documents from the Milvus database. The issue lies in the _search method of the MilvusStore class, where the letter `k` represents the meaning of topk and is set to a default value of 4. However, during the method call, the keyword argument passed is `topk` (instead of `k`), causing the parameter to be ignored and the value of `k` to remain fixed at the default value of 4.
After I modified the keyword argument passed during the method call, the KNOWLEDGE_SEARCH_TOP_SIZE parameter started …
=> fix(milvus): Fix milvus store search with topk always set to 4

dbgpt/agent/core/plan/awel/agent_operator.py, dbgpt/agent/core/plan/awel/agent_operator_resource.py
Close #2097 
core agent dependent prompt service bug (Temporary solution)
```python
import asyncio
import os
from dbgpt.agent import AgentContext, AgentMemory, LLMConfig, UserProxyAgent
from dbgpt.agent.expand.tool_assistant_agent import ToolAssistantAgent
from dbgpt.agent.resource import ToolPack, tool
from dbgpt.model.proxy.llms.chatgpt import OpenAILLMClient
from pydantic import BaseModel, Field
class ArgsSchema(BaseModel):
a: int = Field(description="The first number.")
b: int = Field(description="The second number.")
@tool(args_schema=ArgsSchema)
def two_sum(a: int, b: int) -> int:
"""Add two numbers and return the sum."""
return a + b
tools = ToolPack([two_sum])
async def main():
llm_client = OpenAILLMClient(
model_alias="gpt-4o",
api_base=os.getenv("OPENAI_API_BASE"), …
```
=> fix:core agent dependent prompt service bug

dbgpt/agent/core/profile/base.py
…136)
fix bug (#2136)
prompt after fix
```
human: 最近消息记录:
Question: 使用get_current_system_time获取当前时间戳 
Thought: {
"thought": "用户希望使用get_current_system_time工具来获取当前的时间戳。",
"tool_name": "get_current_system_time",
"args": {}
} 
Observation: 1731575527 
用户输入: Read the result data of the dependent steps in the above historical message to complete the current goal:使用format_time_stamp将时间戳转换为'yy-mm-dd'格式
```
output after fix
```
full stream output:
{
"thought": "为了满足用户需求，需要先从历史消息中提取出当前的时间戳，然后使用format_time_stamp工具将其转换成指定的日期格式。",
"tool_name": "format_time_stamp",
"args": {
"timestamp_str": "1731575527"
}
}
>>>>>>>>LuBan Action report: 
execution succeeded,
24:11:14 17:12:07
```
=> fix the issue that lost prev observation memory in toolExpert bug (#2136)

dbgpt/configs/model_config.py
Support Qwen2.5 coder models.
```bash
LLM_MODEL=qwen2.5-coder-32b-instruct
```
Then, restart your DB-GPT.
=> feat(model): Support Qwen2.5 coder models

dbgpt/_private/config.py, dbgpt/core/interface/llm.py, dbgpt/model/adapter/proxy_adapter.py, dbgpt/model/cluster/manager_base.py, dbgpt/model/cluster/worker/manager.py, dbgpt/model/proxy/__init__.py, dbgpt/model/proxy/base.py, dbgpt/model/proxy/llms/chatgpt.py, dbgpt/model/proxy/llms/claude.py, dbgpt/model/proxy/llms/deepseek.py, dbgpt/model/proxy/llms/gemini.py, dbgpt/model/proxy/llms/moonshot.py, dbgpt/model/proxy/llms/ollama.py, dbgpt/model/proxy/llms/proxy_model.py, dbgpt/model/proxy/llms/spark.py, dbgpt/model/proxy/llms/tongyi.py, dbgpt/model/proxy/llms/wenxin.py, dbgpt/model/proxy/llms/yi.py, dbgpt/model/proxy/llms/zhipu.py, setup.py
Closes #2106 
1. Using `claude` proxyllm in DB-GPT webserver
```shell
LLM_MODEL=claude_proxyllm
ANTHROPIC_MODEL_VERSION=claude-3-5-sonnet-20241022
ANTHROPIC_BASE_URL=https://api.openai-proxy.org/anthropic
ANTHROPIC_API_KEY={your-claude-api-key}
```
2. Using `ClaudeLLMClient`
Create python file `test_proxyllm.py`
```python
import asyncio
from dbgpt.model.proxy import ClaudeLLMClient
client = ClaudeLLMClient(model_alias="claude-3-5-sonnet-20241022")
print(
asyncio.run(
client.generate(
ModelRequest._build("claude-3-5-sonnet-20241022", "Hi, claude!")
)
)
)
```
Run `test_proxyllm.py`
```bash
ANTHROPIC_API_KEY={your-claude-api-key} python test_proxyllm.py
```
The output like this:
```bash
ModelOutput(text="Hi! I'm Claude. How can I help you today?", …
```
=> feat(model): Support claude proxy models

dbgpt/_private/config.py, dbgpt/configs/model_config.py, dbgpt/model/adapter/proxy_adapter.py, dbgpt/model/proxy/__init__.py, dbgpt/model/proxy/llms/siliconflow.py
Closes #2156 
1. Using `siliconflow` proxyllm in DB-GPT webserver
```shell
LLM_MODEL=silicon_flow_proxyllm
SILICON_FLOW_MODEL_VERSION=Qwen/Qwen2.5-Coder-32B-Instruct
SILICON_FLOW_API_BASE=https://api.siliconflow.cn/v1
SILICON_FLOW_API_KEY={your-siliconflow-api-key}
```
2. Using `SiliconFlowLLMClient`
Create python file `test_proxyllm.py`
```python
import asyncio
from dbgpt.model.proxy import SiliconFlowLLMClient
client = SiliconFlowLLMClient(model_alias="Qwen/Qwen2.5-Coder-32B-Instruct")
print(
asyncio.run(
client.generate(
ModelRequest._build("Qwen/Qwen2.5-Coder-32B-Instruct", "Hi!")
)
)
)
```
Run `test_proxyllm.py`
```bash
SILICON_FLOW_API_KEY={your-siliconflow-api-key} python test_proxyllm.py
```
The output like this:
```bash
ModelOutput(text='Hello! …
```
=> feat(model): Support siliconflow models

dbgpt/rag/knowledge/pdf.py, dbgpt/rag/operators/embedding.py, dbgpt/rag/operators/knowledge.py, dbgpt/serve/rag/connector.py, dbgpt/storage/knowledge_graph/community_summary.py, dbgpt/storage/vector_store/chroma_store.py, dbgpt/storage/vector_store/elastic_store.py, dbgpt/storage/vector_store/milvus_store.py, dbgpt/storage/vector_store/oceanbase_store.py, dbgpt/storage/vector_store/pgvector_store.py, dbgpt/storage/vector_store/weaviate_store.py
Close #2166 
- Fix VectorStore can not be attached to EmbeddingAssemblerOperator bug
- add more Vector Store Operators.
=> fix: VectorStore can not be attached to EmbeddingAssemblerOperator bug

dbgpt/app/scene/chat_db/auto_execute/out_parser.py, dbgpt/app/scene/chat_db/auto_execute/prompt.py
Fixed the issue that the `chat data` function occasionally raises "Can not find sql in response" error when there is the answer in the context.
- Chat Data
- make test
=> fix sql not found error for chat data

dbgpt/configs/model_config.py, dbgpt/model/adapter/embeddings_loader.py, dbgpt/model/parameter.py, dbgpt/rag/embedding/__init__.py, dbgpt/rag/embedding/rerank.py
Additions to #2157
1. Using siliconflow rerank models in DB-GPT webserver
```bash
RERANK_MODEL=rerank_proxy_silicon_flow
rerank_proxy_silicon_flow_proxy_server_url=https://api.siliconflow.cn/v1/rerank
rerank_proxy_silicon_flow_proxy_api_key={your-siliconflow-api-key}
rerank_proxy_silicon_flow_proxy_backend=BAAI/bge-reranker-v2-m3
```
2. Using `SiliconFlowRerankEmbeddings`
```python
from dbgpt.rag.embedding import SiliconFlowRerankEmbeddings
embedding = SiliconFlowRerankEmbeddings(api_key='{your_api_key}')
res = embedding.predict("Apple", candidates=["苹果", "香蕉", "水果", "蔬菜"])
print(res)
```
You will see the following output:
```bash
[0.9953725, 0.00046734812, 0.0020992735, 1.7502925e-05]
```
=> feat(model): Support siliconflow rerank models

dbgpt/model/utils/chatgpt_utils.py, dbgpt/rag/operators/knowledge.py
Close #2173 
httpx v0.28.0 proxies bug
[Realease note of httpx v0.28.0](https://github.com/encode/httpx/blob/HEAD/CHANGELOG.md#0280-28th-november-2024)
```python
import asyncio
from dbgpt.model.proxy.llms.chatgpt import OpenAILLMClient  # type: ignore
async def main():
client = OpenAILLMClient(model_alias="gpt-4o-mini")
response = await client.generate(ModelRequest._build("gpt-4o-mini", "Hi!"))
print(response)
asyncio.run(main())
```
=> fix: httpx v0.28.0 proxies bug

.env.template, dbgpt/_private/config.py, dbgpt/configs/model_config.py, dbgpt/model/adapter/embeddings_loader.py, dbgpt/model/adapter/proxy_adapter.py, dbgpt/model/parameter.py, dbgpt/model/proxy/llms/siliconflow.py, dbgpt/rag/assembler/embedding.py, dbgpt/rag/embedding/rerank.py, dbgpt/serve/rag/service/service.py
- Change all 'silicon_flow' to 'siliconflow'
- Fix the bug of `max_chunks_once_load` and `max_threads` missing
See [《DB-GPT + SiliconCloud 使用文档》](https://www.yuque.com/g/chengdian-i8vnz/gxwyag/fsedi9k0lc0lbq7y/collaborator/join?token=T7LDiUNAnQKdeIz8&source=doc_collaborator)
=> chore(model): Modify siliconflow name

dbgpt/agent/core/base_agent.py
After deploying the project, I attempted to complete my functionality using the `agent[Indicator]`, but encountered an error: `'chat abnormal termination! Indicator[Indicator] Missing resources required for runtime!'`. Initially, this error led me to believe that the agent was missing during deployment. However, after debugging, I found that the issue arises because the knowledge base is required when using the Indicator.
I believe that the error log should provide a more detailed explanation of the cause, or there should alert users in UI.
before :
after:
=> Print the necessary resource for the action in error log

dbgpt/app/operators/rag.py, dbgpt/core/awel/flow/base.py, dbgpt/rag/operators/__init__.py, dbgpt/rag/operators/chunk_manager.py, dbgpt/rag/operators/full_text.py, dbgpt/rag/operators/knowledge_graph.py, dbgpt/rag/operators/process_branch.py, dbgpt/rag/operators/vector_store.py, dbgpt/serve/agent/resource/knowledge.py, dbgpt/serve/flow/templates/en/embedded-knowledge-process-flow-template.json, dbgpt/serve/flow/templates/en/hybrid-knowledge-process-template.json, dbgpt/serve/flow/templates/en/kg-knowledge-process-flow-template.json, dbgpt/serve/flow/templates/zh/embedded-knowledge-process-flow-template.json, dbgpt/serve/flow/templates/zh/hybrid-knowldge-process-flow-template.json, dbgpt/serve/flow/templates/zh/kg-knowledge-process-flow-template.json, dbgpt/serve/rag/api/schemas.py, dbgpt/serve/rag/service/service.py, dbgpt/storage/knowledge_graph/community_summary.py, dbgpt/storage/knowledge_graph/knowledge_graph.py, docs/docs/awel/awel_tutorial/templates/Embedding.md, docs/docs/awel/awel_tutorial/templates/Hybrid_Workflow.md, docs/docs/awel/awel_tutorial/templates/Knowledge_Graph.md, docs/sidebars.js
Close #2192 
Close #2191 
- Add Embedding Process AWEL Template
- Add KG Process AWEL Template
- Add Hybrid Knowledge Process AWEL Template
- Add More Knowledge Process Operators
1. Import knowledge process awel template
2. save
3. test with curl 
```
curl --location --request POST 'http://localhost:5670/api/v1/awel/trigger/rag/knowledge/hybrid/process' \
--header 'Content-Type: application/json' \
-d '{}'
```
Results
```
[
"async persist vector store success 9 chunks.",
"async persist graph store success 9 chunks."
]
```
=> feat:Add Knowledge Process Workflow

.github/workflows/docker-image-publish.yml
Previously, the DB-GPT docker image build failed due to the large disk space occupied, such as https://github.com/eosphoros-ai/DB-GPT/actions/runs/11967971790
I fixed it according to https://github.com/orgs/community/discussions/26351#discussioncomment-3251595
It works on [my workflow](https://github.com/fangyinc/DB-GPT/actions/runs/12410571824/job/34646481309)
This is the image uploaded by [my workflow](https://github.com/fangyinc/DB-GPT/actions/runs/12410571824/job/34646481309)
=> fix(ci): Fix build docker image error

dbgpt/datasource/conn_tugraph.py, dbgpt/storage/graph_store/base.py, dbgpt/storage/graph_store/tugraph_store.py, dbgpt/storage/knowledge_graph/community_summary.py, dbgpt/storage/knowledge_graph/knowledge_graph.py
Close #2214 
fix create same graph name error.
- create graph space name and upload document
- delete graph space name
- create same graph space and upload document again.
=> fix(GraphRAG): create same graph name error.

.env.template, dbgpt/_private/config.py, dbgpt/agent/core/agent.py, dbgpt/agent/core/base_agent.py, dbgpt/agent/core/base_team.py, dbgpt/agent/core/memory/gpts/base.py, dbgpt/agent/core/memory/gpts/gpts_memory.py, dbgpt/agent/core/plan/awel/team_awel_layout.py, dbgpt/agent/core/plan/planner_agent.py, dbgpt/agent/core/user_proxy_agent.py, dbgpt/serve/agent/agents/controller.py, dbgpt/serve/agent/agents/expand/app_start_assisant_agent.py, dbgpt/serve/agent/db/gpts_app.py
Closes #2219
Closes #2206
Agent supports conversation context historical message.
Use directly in Agent application conversations.
Modify the following env configuration properties to adjust the range：
MESSAGES_KEEP_START_ROUNDS=0
MESSAGES_KEEP_END_ROUNDS=2
=> feat(agent):Agent supports conversation context

dbgpt/serve/rag/connector.py, dbgpt/storage/vector_store/chroma_store.py
Resolved the issue of repeatedly creating the same database, which prevented the creation of a vector store with identical metadata.
Repeatedly creating and deleting the same database ensures that the vector store with metadata is created correctly.
=> Fix Bug #2224

dbgpt/core/schema/api.py, dbgpt/model/adapter/base.py, dbgpt/model/adapter/llama_cpp_adapter.py, dbgpt/model/adapter/loader.py, dbgpt/model/adapter/model_adapter.py, dbgpt/model/base.py, dbgpt/model/cluster/apiserver/api.py, dbgpt/model/cluster/base.py, dbgpt/model/cluster/worker/default_worker.py, dbgpt/model/cluster/worker/remote_worker.py, dbgpt/model/llm/llama_cpp/llama_cpp.py, docs/docs/installation/advanced_usage/Llamacpp_server.md, docs/sidebars.js, setup.py
1. Support [llama.cpp server](https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md) inference
2. API Server support `/v1/completions`  
3. Support native generate function 
```bash
pip install -e ".[llama_cpp_server]"
```
If you want to accelerate the inference speed, and you have a GPU, you can install the following dependencies:
```bash
CMAKE_ARGS="-DGGML_CUDA=ON" pip install -e ".[llama_cpp_server]"
```
Here, we use the `qwen2.5-0.5b-instruct` model as an example. You can download the model from the [Huggingface](https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF).
```bash
wget https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF/resolve/main/qwen2.5-0.5b-instruct-q4_k_m.gguf?download=true -O /tmp/qwen2.5-0.5b-instruct-q4_k_m.gguf
````
In the `.env` …
=> feat(model): Support llama.cpp server deploy

dbgpt/serve/agent/hub/plugin_hub.py
This PR fixes a critical path traversal vulnerability (CVE-2024-10834) in the plugin upload functionality. The vulnerability could allow attackers to write files to arbitrary locations on the filesystem through maliciously crafted filenames.
- Added filename sanitization to remove unsafe characters and path components
- Implemented path validation to prevent directory traversal attempts
- Added secure temporary file handling with proper cleanup
- Improved error handling for failed uploads
- **Vulnerability**: Path Traversal (CWE-22)
- **CVSS Score**: 7.5 (High)
- **Affected Versions**: All versions before this fix
- **Fixed Versions**: Current PR
The fix has been tested against:
- Basic file uploads
- Filenames with special characters
- Directory traversal attempts
- Error cases and …
=> fix(security): fix path traversal vulnerability (CVE-2024-10834)

dbgpt/agent/resource/app.py, dbgpt/agent/resource/base.py, dbgpt/app/component_configs.py, dbgpt/serve/agent/agents/app_agent_manage.py, dbgpt/serve/agent/agents/expand/__init__.py, dbgpt/serve/agent/agents/expand/app_resource_start_assisant_agent.py
在多Agent的角色中增加了一个AppStarter角色，可以在前端直接选目标APP进行启动。
- [*] My code follows the style guidelines of this project
- [*] I have already rebased the commits and make the commit message conform to the project standard.
- [*] I have performed a self-review of my own code
- [*] I have commented my code, particularly in hard-to-understand areas
- [*] I have made corresponding changes to the documentation
- [*] Any dependent changes have been merged and published in downstream modules
=> feat(agent): add app starter role in mutli agent

.github/workflows/doc-image-publish.yml, docs/Dockerfile-deploy, docs/patchs/fix_0.6.3.patch
Resolve a document build error by modifying the CI workflow and adding a patch application step. Update the sidebars.js file to correct a syntax issue.
```bash
NPM_REGISTRY=https://registry.npmmirror.com
docker build -f docs/Dockerfile-deploy \
-t eosphorosai/dbgpt-docs \
--build-arg NPM_REGISTRY=$NPM_REGISTRY \
--build-arg CI=false \
--build-arg NUM_VERSION=1 .
```
=> fix(docs): Fix document build error

dbgpt/agent/resource/app.py, dbgpt/app/component_configs.py, dbgpt/serve/agent/agents/app_agent_manage.py, dbgpt/serve/agent/agents/expand/__init__.py, dbgpt/serve/agent/agents/expand/app_resource_start_assisant_agent.py
fix some format problem
- [*] My code follows the style guidelines of this project
- [*] I have already rebased the commits and make the commit message conform to the project standard.
- [*] I have performed a self-review of my own code
- [*] I have commented my code, particularly in hard-to-understand areas
- [*] I have made corresponding changes to the documentation
- [*] Any dependent changes have been merged and published in downstream modules
=> fix(agent): format problem

dbgpt/app/openapi/api_v1/editor/api_editor_v1.py
This PR fixes a critical security vulnerability (CVE-2024-10835) in the SQL editor API that could allow attackers to perform arbitrary file write operations through DuckDB SQL queries. The vulnerability could potentially lead to Remote Code Execution (RCE).
Key changes:
- Added database type validation to identify DuckDB connections
- Implemented comprehensive dangerous operation filtering for DuckDB
- Added SQL execution timeout protection (30s)
- Added file path pattern detection to block file operations
- Improved logging for security events
- Enhanced type conversion safety
The security fix has been tested with:
1. Normal SQL Operations:
- Standard SELECT queries
- JOIN operations
- Aggregate functions
- Sub-queries
2. Security Tests:
- File operation attempts via DuckDB
- System …
=> fix(security): prevent arbitrary file write in SQL editor (CVE-2024-10835)

dbgpt/app/openapi/api_v1/editor/api_editor_v1.py
This PR fixes a SQL injection vulnerability in the chart data query API that could allow attackers to perform arbitrary file operations through DuckDB SQL queries. This is related to CVE-2024-10835 and implements similar protections in the chart functionality.
Key changes:
- Added SQL validation for chart queries
- Implemented dangerous operation filtering
- Added timeout protection
- Enhanced input validation
- Improved type safety in data processing
1. Functional Testing:
- All supported chart types
- Various data types and volumes
- Complex SQL queries
- Timeout scenarios
2. Security Testing:
- SQL injection attempts
- File operation attempts
- System command execution attempts
- Various bypass attempts
=> fix(security): prevent SQL injection in chart data query (CVE-2024-10901)

dbgpt/agent/resource/app.py, dbgpt/serve/agent/agents/controller.py
Ensure proper initialization of application modules and enhance the resource parameters handling for agent.
In this [dbgpt/agent/resource/app.py#L34](https://github.com/eosphoros-ai/DB-GPT/blob/22249840de9e04eabb1098b707684444300d17a2/dbgpt/agent/resource/app.py#L34), the database is read in advance before it is initialized.
Closes #2184
Closes #2287
Closes #2163
Clone a new DB-GPT project, run it with SQLite database.
=> fix(agent): Fix load db models error

dbgpt/util/json_utils.py, dbgpt/util/tests/test_json_utils.py
=> fix(json_utils): fix function find_json_objects

packages/dbgpt-app/src/dbgpt_app/component_configs.py, packages/dbgpt-core/src/dbgpt/agent/resource/app.py, packages/dbgpt-serve/src/dbgpt_serve/agent/resource/app.py
move app resource implement to serv pkg
on web chat
- [ * ] My code follows the style guidelines of this project
- [ * ] ] I have already rebased the commits and make the commit message conform to the project standard.
- [ * ]] I have performed a self-review of my own code
- [ * ]] I have commented my code, particularly in hard-to-understand areas
- [ * ] ] I have made corresponding changes to the documentation
- [ * ] ] Any dependent changes have been merged and published in downstream modules
=> fix(agent): move app resource implement to serv pkg

.github/workflows/code-checks.yml, .github/workflows/pylint.yml, Makefile, packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/milvus_store.py, pyproject.toml
=> workflow(ruff): add ruff code checks workflow

packages/dbgpt-core/src/dbgpt/model/cluster/embedding/remote_embedding.py
The previous implementation incorrectly used the `await` keyword directly on the indexing operation, which caused a `TypeError` when `enable_summary="True"` was set. like
> 2025-03-11 19:14:25 hostname dbgpt_serve.rag.service.service[788143] ERROR document embedding, failed:74.txt, RetryError[<Future at 0x7b5c86f44f90 state=finished raised TypeError>]
The fix involves awaiting the result of the asynchronous `aembed_documents` method before indexing. This change ensures that the asynchronous operation is handled correctly, preventing the error.
Pass!
=> fix: aembed_query type error

.github/workflows/docker-image-publish-openai.yml, .github/workflows/docker-image-publish.yml, docker/base/Dockerfile
=> fix(docker): Fix build arm image bug

packages/dbgpt-ext/src/dbgpt_ext/datasource/rdbms/dialect/starrocks/sqlalchemy/__init__.py, packages/dbgpt-ext/src/dbgpt_ext/datasource/rdbms/dialect/starrocks/sqlalchemy/dialect.py
fix https://github.com/eosphoros-ai/DB-GPT/issues/2453
Version 0.7.0 changes the code package structure, and the path to register the database dialect changes and needs to be changed
make fmt
make mypy
make test
- [x ] My code follows the style guidelines of this project
=> fix(datasource): Correct the import path for StarRocks dialect

packages/dbgpt-core/src/dbgpt/core/interface/message.py, packages/dbgpt-serve/src/dbgpt_serve/agent/db/gpts_app.py, packages/dbgpt-serve/src/dbgpt_serve/agent/db/gpts_conversations_db.py, packages/dbgpt-serve/src/dbgpt_serve/agent/db/gpts_messages_db.py
- 在推荐问题的数据库记录中添加用户码字段
- 通过 gpts_app.user_code 获取当前用户码并存储
Closes #2426
recommend_question
- [ x] My code follows the style guidelines of this project
- [x ] I have already rebased the commits and make the commit message conform to the project standard.
- [x ] I have performed a self-review of my own code
=> feat(dbgpt-serve): Agent fixes and parameter additions

packages/dbgpt-app/src/dbgpt_app/operators/rag.py, packages/dbgpt-core/src/dbgpt/core/awel/flow/base.py, packages/dbgpt-core/src/dbgpt/core/awel/flow/compat.py, packages/dbgpt-core/src/dbgpt/core/awel/flow/flow_factory.py, packages/dbgpt-core/src/dbgpt/util/cli/flow_compat.py, packages/dbgpt-core/src/dbgpt/vis/tags/vis_chart.py, packages/dbgpt-core/src/dbgpt/vis/tags/vis_dashboard.py, packages/dbgpt-serve/src/dbgpt_serve/flow/compat/0.7.0_compat_flow.json, packages/dbgpt-serve/src/dbgpt_serve/flow/service/service.py, packages/dbgpt-serve/src/dbgpt_serve/flow/templates/en/embedded-knowledge-process-flow-template.json, packages/dbgpt-serve/src/dbgpt_serve/flow/templates/en/hybrid-knowledge-process-template.json, packages/dbgpt-serve/src/dbgpt_serve/flow/templates/en/kg-knowledge-process-flow-template.json, packages/dbgpt-serve/src/dbgpt_serve/flow/templates/en/rag-chat-awel-flow-template.json, packages/dbgpt-serve/src/dbgpt_serve/flow/templates/zh/embedded-knowledge-process-flow-template.json, packages/dbgpt-serve/src/dbgpt_serve/flow/templates/zh/hybrid-knowldge-process-flow-template.json, packages/dbgpt-serve/src/dbgpt_serve/flow/templates/zh/kg-knowledge-process-flow-template.json, packages/dbgpt-serve/src/dbgpt_serve/flow/templates/zh/rag-chat-awel-flow-template.json
Closes #2444
Closes #2448
Closes #2418
Closes #2399
=> fix(awel): Fix AWEL flow error

packages/dbgpt-app/src/dbgpt_app/knowledge/service.py
The knowledgebase recall test did not respond to anything, and the log showed an error:
' dbgpt_app.knowledge.service[25544] ERROR  recall_test error: 'NoneType' object has no attribute 'config''
and debug the code find missing system_app param
=> fix(knowledge recall test): Add system_app parameter to knowledgeSpaceRetriever initialization

packages/dbgpt-app/src/dbgpt_app/knowledge/service.py, packages/dbgpt-core/src/dbgpt/rag/transformer/llm_extractor.py
Update the extract function to check for empty response before parsing
- [] I have commented my code, particularly in hard-to-understand areas
=> fix(LLM extractor): handle empty response in LLM extractor

packages/dbgpt-ext/src/dbgpt_ext/datasource/rdbms/conn_doris.py
#Description
When working with Doris as a data source for visualization, I discovered that the vector data queried lacked the corresponding table comments. This absence of table comments was causing a decrease in matching accuracy. To address this issue, I implemented a solution by rewriting the get_table_comment method in the conn_doris module. This enhancement ensures proper retrieval and association of table comments with the vector data, ultimately improving the overall accuracy of data matching and visualization results.
=> fix:doris_conn cannot get table comment to store vectordb

packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/milvus_store.py
line 564: 
param = self.index_params_map[index_type].get("params") should remove get("params");
查询 milvus 的时候，逻辑是：_search 方法的 param 参数为 None 时，会读取 index_params_map 对应索引的配置参数。但是不应再调用 get("params")，会导致传递给 milvus 的 search 参数是错误的格式，使得参数无效，milvus 会以它自己的默认参数查询。可以参考 milvus 官网：https://milvus.io/api-reference/pymilvus/v2.5.x/MilvusClient/Vector/search.md
=> fix: milvus collection search param

packages/dbgpt-serve/src/dbgpt_serve/rag/service/service.py
When editing the name of a KB document, if there are no question and answer pairs by default, the frontend will not pass the questions field, and the questions on the backend are None instead of empty list
=> fix(knowledge):Fix KB document questions list check logic

packages/dbgpt-core/src/dbgpt/agent/expand/actions/react_action.py, packages/dbgpt-core/src/dbgpt/agent/expand/actions/tool_action.py, packages/dbgpt-core/src/dbgpt/agent/resource/tool/pack.py, packages/dbgpt-core/src/dbgpt/agent/util/mcp_utils.py, packages/dbgpt-core/src/dbgpt/model/proxy/llms/chatgpt.py, packages/dbgpt-serve/src/dbgpt_serve/agent/resource/mcp.py
- Support SSL/TLS for MCP
- Fix tool emply list bug
```python
tools = MCPToolPack(
"https://your_ssl_domain/sse",
)
tools2 = MCPToolPack(
"https://your_ssl_domain/sse", default_ssl_verify=False
)
tools3 = MCPToolPack(
"https://your_ssl_domain/sse", default_ssl_cafile="/path/to/your/ca.crt"
)
import ssl
tools4 = MCPToolPack(
"https://your_ssl_domain/sse",
ssl_verify={
"https://your_ssl_domain/sse": ssl.create_default_context(
cafile="/path/to/your/ca.crt"
),
},
)
```
Webpage:
=> feat(agent): Support  SSL/TLS for MCP

assets/schema/dbgpt.sql, assets/schema/upgrade/v0_7_1/upgrade_to_v0.7.1.sql, assets/schema/upgrade/v0_7_1/v0.7.0.sql
- Update flow_data column type in dbgpt_serve_flow table from text to longtext
- Modify flow_data column type in v0.7.0.sql and upgrade_to_v0.7.1.sql
When there are too many workflow nodes, saving the workflow will error flow_data data fields are too long
Just change the flow_data field type text to longtext
N/A
=> fix(schema): change flow_data column type from text to longtext

packages/dbgpt-ext/src/dbgpt_ext/datasource/rdbms/conn_postgresql.py
When using PostgreSQL as a metadata db, the application starts incorrectly ...
**psycopg2.ProgrammingError: invalid dsn: invalid connection option "charset"**
The db_url method of the default MySQL uses the chartset parameter, which is not valid in the PostgreSQL scenario
We need to override the db_url method in the PostgreSQL Connector
The app is able to launch successfully
=> Fix postgresql

examples/agents/react_agent_example.py, packages/dbgpt-core/src/dbgpt/agent/core/memory/long_term.py, packages/dbgpt-core/src/dbgpt/model/cluster/apiserver/api.py, packages/dbgpt-core/src/dbgpt/model/cluster/base.py
1. Wrong worker_type causes remote reranker call to fail
2. when use hybrid memory in agent, datetime obj in long_term memory is never written to Chroma metadata
=> fix(model): fix remote reranker api & fix long_term memory

packages/dbgpt-app/src/dbgpt_app/openapi/api_v1/editor/api_editor_v1.py, packages/dbgpt-core/src/dbgpt/datasource/rdbms/base.py
**Version: 0.7.0**
An SQL injection vulnerability exists in DB-GPT 0.7.0 despite fixes for prior CVEs (CVE-2024-10835 and CVE-2024-10901). Both `/v1/editor/sql/run` and `/v1/editor/chart/run` endpoints remain vulnerable to SQL injection. The previous patches implemented blacklist-based protections only for DuckDB connections, but failed to address the root cause: direct execution of user-provided SQL without proper parameterization.
The incomplete fix:
- Added security controls exclusively for DuckDB connections.
- Used a blacklist approach that can be bypassed with SQL obfuscation.
- Left all other database types (MySQL, PostgreSQL, etc.) completely vulnerable.
- Failed to implement proper parameterized queries via SQLAlchemy.
1. **Source:** `editor_sql_run()` in …
=> [BUG] SQL Injection through CVE Bypass in DB-GPT 0.7.0 (CVE-2024-10835 & CVE-2024-10901)

packages/dbgpt-core/src/dbgpt/agent/expand/actions/chart_action.py
By default,the sql execution result of DataScientistis Agent displayed only in vis chart, if you want to use the Summary Agent to summarize the results of DataScientistis Agent, you can only analyze whether the SQL execution is correct, but cannot analyze the data queried by the SQL, which does not meet our expectations,I pass the SQL query results to the Content node. Other agents can do the  processing
=> feat(agent): The SQL execution result of the DataScientist can be passed to the next agent

examples/rag/doc_tree_retriever_example.py, packages/dbgpt-core/src/dbgpt/core/interface/knowledge.py, packages/dbgpt-core/src/dbgpt/rag/knowledge/base.py, packages/dbgpt-core/src/dbgpt/storage/base.py, packages/dbgpt-ext/src/dbgpt_ext/rag/knowledge/markdown.py, packages/dbgpt-ext/src/dbgpt_ext/rag/retriever/doc_tree.py
Close #2667 
- tree retriever based on document directory level
`python examples/rag/doc_tree_retriever_example.py `
```
Query: Introduce awel Operators
├── Operators (node_id: 2df9b1f8-8985-4d9c-9b17-7c51ba043113)
│   ├── Example of API-RAG (node_id: 2df9b1f8-8985-4d9c-9b17-7c51ba043113)
│   └── ├── Example of LLM + cache (node_id: bfb92889-87e5-47e7-b7d0-687b9d994fd0)
│   ├── AgentFream Example (node_id: 5619ac28-f914-4c4b-89ca-2f072603e9da)
└── ├── DSL Example (node_id: 8ce55af9-1917-49c1-8ecd-b61405898704)
```
=> feat(RAG):add tree retriever based on document directory level

packages/dbgpt-app/src/dbgpt_app/knowledge/_cli/knowledge_client.py, packages/dbgpt-app/src/dbgpt_app/scene/base_chat.py, packages/dbgpt-core/src/dbgpt/agent/resource/tool/autogpt/plugins_util.py, packages/dbgpt-core/src/dbgpt/core/awel/dag/base.py, packages/dbgpt-core/src/dbgpt/model/adapter/loader.py, packages/dbgpt-core/src/dbgpt/model/cluster/worker/manager.py, packages/dbgpt-core/src/dbgpt/model/proxy/base.py, packages/dbgpt-core/src/dbgpt/model/utils/token_utils.py, packages/dbgpt-core/src/dbgpt/storage/cache/manager.py, packages/dbgpt-core/src/dbgpt/util/model_utils.py, packages/dbgpt-core/src/dbgpt/util/speech/eleven_labs.py, packages/dbgpt-serve/src/dbgpt_serve/datasource/service/db_summary_client.py
This PR resolves the deprecation warnings of the `logger` library:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
Tests
=> Resolve warnings of logger library

packages/dbgpt-app/src/dbgpt_app/scene/chat_dashboard/chat.py, packages/dbgpt-core/src/dbgpt/core/interface/prompt.py
Fixes #2694
修复chat_dashboard场景下自定义提示词模板变量名不匹配的问题。
=> fix: resolve KeyError: 'question' in chat_dashboard prompt template

.devcontainer/Dockerfile.dev, .devcontainer/post-create.sh, packages/dbgpt-core/src/dbgpt/storage/base.py
Fixes #2710 
- fix: handle exceptions in aload_document_with_limit results
- The `_run_tasks_with_concurrency` method uses `return_exceptions=True`, which allows `results` to contain both successful outputs and Exception objects. The original code assumed all `success_ids` were lists of strings, leading to potential `AttributeError` (e.g., iterating an Exception object) or incorrect ID aggregation.
- This commit adds a check for `isinstance(success_ids, Exception)`. If an Exception is detected, it is raised explicitly to avoid silent failure and ensure only valid chunk IDs are collected.  
- feat: add devcontainer `zh_CN` LANG support
=> Bugfix(RAG):handle exceptions in aload_document_with_limit results

packages/dbgpt-app/src/dbgpt_app/scene/base_chat.py, packages/dbgpt-app/src/dbgpt_app/scene/chat_dashboard/chat.py, packages/dbgpt-serve/src/dbgpt_serve/prompt/models/models.py
fix chat scene use custom prompt template problem. It has [response]、[question] keyword parsed exception
Closes #2628 
1. create new prompt template with scene type
2. use it in chat data scene
=> fix(scene): fix chat scene config custom prompt

packages/dbgpt-core/src/dbgpt/rag/retriever/base.py, packages/dbgpt-core/src/dbgpt/storage/base.py, packages/dbgpt-ext/src/dbgpt_ext/rag/retriever/doc_tree.py, packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/chroma_store.py, packages/dbgpt-ext/src/dbgpt_ext/storage/vector_store/milvus_store.py, packages/dbgpt-serve/src/dbgpt_serve/rag/api/endpoints.py, packages/dbgpt-serve/src/dbgpt_serve/rag/retriever/knowledge_space.py, packages/dbgpt-serve/src/dbgpt_serve/rag/service/service.py
Close #2668  
Add hybrid search for knowledge space. 
- semantic search
- keyword full text search for milvus
- doc tree search
ChatKnowledge and check log.
```
Hybrid retrieval completed. Found 3 semantic candidates and Found 0 full text candidates.and Found 1 tree candidates.
```
=> feat(ChatKnowledge):add hybrid search for knowledge space. 

packages/dbgpt-app/src/dbgpt_app/operators/datasource.py, packages/dbgpt-serve/src/dbgpt_serve/flow/compat/0.7.0_compat_flow.json
- Add a new operator to structure the output of database workflow execution results. This operator provides users with a structured representation of workflow execution outcomes, decoupling them from the frontend visualization architecture. This enhancement allows users to flexibly utilize workflow output data.   
- Output format:  
```json
{
"data": [
{
"thoughts": "query something",
"sql": "sql",
"display_type": "response_table",
"data": [
]
}
]
}
```
=> feat(AWEL):Add operator for structured output data of datasource in AWEL

packages/dbgpt-core/src/dbgpt/agent/expand/actions/chart_action.py
1. The count field is added to the DataScientist action output result, so that the summarizer can correctly obtain the number of data records
2. fixbug #2741 DataScientist action output is converted to json,  ASCII escaping is not disabled, when there is Chinese data, it will be changed to unicode characters, so there will be errors when the summary agent recognizes unicode
=> feat(agent): Add count field and support non-ASCII characters in DataScientist action output
